# Generated by msgspec-serde. DO NOT EDIT.
# Source: //schemas/reading_v1.fbs
from __future__ import annotations

import struct
from typing import overload

import msgspec
import numpy as np
import numpy.typing as npt

from msgspec_serde import _check_generated_code_version

__msgspec_serde_generated_version__ = '0.1.0'
_check_generated_code_version(__msgspec_serde_generated_version__)

from msgspec_serde import (  # noqa: E402
    DynamicModelOverrides,
    InvalidBufferError,
    TableView as _FbTableView,
)
from msgspec_serde._models import resolve_model_types as _resolve_model_types  # noqa: E402
from msgspec_serde._native import NativePlan as _NativePlan  # noqa: E402
from msgspec_serde._flatbuffer import register_type as _register_flatbuffer_type  # noqa: E402

_UINT16 = struct.Struct('<H')
_UINT64 = struct.Struct('<Q')

_FB_NATIVE_MODULE = _NativePlan(b'\x82\xa7version\x02\xa7objects\x91\x88\xa4name\xb9Example.Evolution.Reading\xa9is_struct\xc2\xa9byte_size\x00\xadmin_alignment\x01\xa6fields\x93\x89\xa4name\xa2id\xa4slot\x00\xa6offset\x04\xa8optional\xc2\xa8required\xc2\xa7default\x00\xaeserde_nullable\xc2\xa4kind\xa6scalar\xa6scalar\xa6uint64\x88\xa4name\xa5label\xa4slot\x01\xa6offset\x06\xa8optional\xc3\xa8required\xc2\xa7default\xc0\xaeserde_nullable\xc3\xa4kind\xa6string\x89\xa4name\xa7samples\xa4slot\x02\xa6offset\x08\xa8optional\xc3\xa8required\xc2\xa7default\xc0\xaeserde_nullable\xc3\xa4kind\xadvector_scalar\xa6scalar\xa7float32\xacserde_fields\x93\x82\xa9attr_name\xa2id\xabencode_name\xa2id\x82\xa9attr_name\xa5label\xabencode_name\xa5label\x82\xa9attr_name\xa7samples\xabencode_name\xa7samples\xafserde_tag_field\xc0\xa9serde_tag\xc0')


class Reading(msgspec.Struct, kw_only=True, eq=False):
    id: int = 0
    label: str | None = None
    samples: npt.NDArray[np.float32] | None = None

    def __eq__(self, other: object) -> bool:
        if type(other) is not type(self):
            return False
        return (
            (self.id == other.id)
            and (self.label == other.label)
            and ((self.samples is None and other.samples is None) or (self.samples is not None and other.samples is not None and self.samples.dtype == other.samples.dtype and np.array_equal(self.samples, other.samples)))
        )

    def __ne__(self, other: object) -> bool:
        return not self == other


class ReadingView(_FbTableView):
    __slots__ = ('_fb_cached_label', '_fb_cached_samples')
    __flatbuffer_identifier__ = b'EVOL'

    @property
    def id(self) -> int:
        if 4 >= self._vtable_size:
            value = 0
        else:
            value_relative = _UINT16.unpack_from(self._buffer, self._vtable_offset + 4)[0]
            if value_relative == 0:
                value = 0
            elif value_relative < 4 or value_relative > self._object_size - 8:
                raise InvalidBufferError("field lies outside its FlatBuffers table")
            else:
                value = _UINT64.unpack_from(self._buffer, self._table_offset + value_relative)[0]
        return value

    @property
    def label(self) -> str | None:
        try:
            value = self._fb_cached_label
        except AttributeError:
            value = self._read_string(6)
            self._fb_cached_label = value
        return value

    @property
    def samples(self) -> npt.NDArray[np.float32] | None:
        try:
            value = self._fb_cached_samples
        except AttributeError:
            value = self._read_numpy_vector(8, '<f4')
            self._fb_cached_samples = value
        return value

    @overload
    def to_model(
        self,
        *,
        dynamic_overrides: DynamicModelOverrides | None = None,
    ) -> Reading: ...

    @overload
    def to_model[_ModelT: Reading](
        self,
        model_type: type[_ModelT],
        *,
        dynamic_overrides: DynamicModelOverrides | None = None,
    ) -> _ModelT: ...

    def to_model(
        self,
        model_type: type[Reading] = Reading,
        *,
        dynamic_overrides: DynamicModelOverrides | None = None,
    ) -> Reading:
        if model_type is Reading and dynamic_overrides is None:
            return _FB_NATIVE_MODULE.unpack_view(
                'Example.Evolution.Reading',
                self._buffer,
                self._table_offset,
            )
        native_types = None if model_type is Reading else _resolve_model_types(
            _FB_NATIVE_MODULE, Reading, model_type
        )
        return _FB_NATIVE_MODULE.unpack_view(
            'Example.Evolution.Reading',
            self._buffer,
            self._table_offset,
            model_types=native_types,
            dynamic_overrides=dynamic_overrides,
        )


_FB_NATIVE_MODULE.bind_types({
    'Example.Evolution.Reading': Reading,
})


_register_flatbuffer_type(Reading, _FB_NATIVE_MODULE, 'Example.Evolution.Reading', 'EVOL')


__all__ = ['Reading', 'ReadingView']
