# Generated by msgspec-flatbuffers. DO NOT EDIT.
# Source: //schemas/reading_v2.fbs
from __future__ import annotations

import struct

import msgspec
import numpy as np
import numpy.typing as npt

from msgspec_flatbuffers import (
    InvalidBufferError,
    OpenIntEnum,
    StringVector,
    StructVector,
    StructView,
    TableVector,
    TableView,
)
from msgspec_flatbuffers._native import NativePlan as _NativePlan

_UINT16 = struct.Struct('<H')
_UINT64 = struct.Struct('<Q')
_UINT8 = struct.Struct('<B')

_FB_NATIVE_MODULE = _NativePlan(b'\x82\xa7version\x01\xa7objects\x91\x85\xa4name\xb9Example.Evolution.Reading\xa9is_struct\xc2\xa9byte_size\x00\xadmin_alignment\x01\xa6fields\x95\x88\xa4name\xa2id\xa4slot\x00\xa6offset\x04\xa8optional\xc2\xa8required\xc2\xa7default\x00\xa4kind\xa6scalar\xa6scalar\xa6uint64\x87\xa4name\xa5label\xa4slot\x01\xa6offset\x06\xa8optional\xc3\xa8required\xc2\xa7default\xc0\xa4kind\xa6string\x88\xa4name\xa7samples\xa4slot\x02\xa6offset\x08\xa8optional\xc3\xa8required\xc2\xa7default\xc0\xa4kind\xadvector_scalar\xa6scalar\xa7float32\x88\xa4name\xa7quality\xa4slot\x03\xa6offset\n\xa8optional\xc2\xa8required\xc2\xa7defaultd\xa4kind\xa6scalar\xa6scalar\xa5uint8\x87\xa4name\xa4note\xa4slot\x04\xa6offset\x0c\xa8optional\xc3\xa8required\xc2\xa7default\xc0\xa4kind\xa6string')


class Reading(msgspec.Struct, frozen=True, kw_only=True, eq=False):
    id: int = 0
    label: str | None = None
    samples: npt.NDArray[np.float32] | None = None
    quality: int = 100
    note: str | None = None

    def __eq__(self, other: object) -> bool:
        if type(other) is not Reading:
            return False
        return (
            (self.id == other.id)
            and (self.label == other.label)
            and ((self.samples is None and other.samples is None) or (self.samples is not None and other.samples is not None and self.samples.dtype == other.samples.dtype and np.array_equal(self.samples, other.samples)))
            and (self.quality == other.quality)
            and (self.note == other.note)
        )

    def __ne__(self, other: object) -> bool:
        return not self == other

    @classmethod
    def from_flatbuffer(
        cls,
        buffer: bytes | bytearray | memoryview,
        *,
        offset: int = 0,
        size_prefixed: bool = False,
        check_identifier: bool = True,
    ) -> Reading:
        return _FB_NATIVE_MODULE.unpack(
            'Example.Evolution.Reading',
            buffer,
            identifier='EVOL',
            offset=offset,
            size_prefixed=size_prefixed,
            check_identifier=check_identifier,
        )

    def to_flatbuffer(
        self,
        *,
        size_prefixed: bool = False,
        initial_size: int = 0,
    ) -> memoryview:
        return _FB_NATIVE_MODULE.pack(
            'Example.Evolution.Reading',
            self,
            identifier='EVOL',
            size_prefixed=size_prefixed,
            initial_size=initial_size,
        )


_FB_NATIVE_MODULE.bind_types({
    'Example.Evolution.Reading': Reading,
})


class ReadingView(TableView):
    __slots__ = ('_fb_cached_label', '_fb_cached_samples', '_fb_cached_note')
    __flatbuffer_identifier__ = b'EVOL'

    @property
    def id(self) -> int:
        if 4 >= self._vtable_size:
            value = 0
        else:
            value_relative = _UINT16.unpack_from(self._buffer, self._vtable_offset + 4)[0]
            if value_relative == 0:
                value = 0
            elif value_relative < 4 or value_relative > self._object_size - 8:
                raise InvalidBufferError("field lies outside its FlatBuffers table")
            else:
                value = _UINT64.unpack_from(self._buffer, self._table_offset + value_relative)[0]
        return value

    @property
    def label(self) -> str | None:
        try:
            value = self._fb_cached_label
        except AttributeError:
            value = self._read_string(6)
            self._fb_cached_label = value
        return value

    @property
    def samples(self) -> npt.NDArray[np.float32] | None:
        try:
            value = self._fb_cached_samples
        except AttributeError:
            value = self._read_numpy_vector(8, '<f4')
            self._fb_cached_samples = value
        return value

    @property
    def quality(self) -> int:
        if 10 >= self._vtable_size:
            value = 100
        else:
            value_relative = _UINT16.unpack_from(self._buffer, self._vtable_offset + 10)[0]
            if value_relative == 0:
                value = 100
            elif value_relative < 4 or value_relative > self._object_size - 1:
                raise InvalidBufferError("field lies outside its FlatBuffers table")
            else:
                value = _UINT8.unpack_from(self._buffer, self._table_offset + value_relative)[0]
        return value

    @property
    def note(self) -> str | None:
        try:
            value = self._fb_cached_note
        except AttributeError:
            value = self._read_string(12)
            self._fb_cached_note = value
        return value

    def to_model(self) -> Reading:
        return _FB_NATIVE_MODULE.unpack_view(
            'Example.Evolution.Reading',
            self._buffer,
            self._table_offset,
        )


def build_reading(
    value: Reading,
    *,
    size_prefixed: bool = False,
    initial_size: int = 0,
) -> memoryview:
    return _FB_NATIVE_MODULE.pack(
        'Example.Evolution.Reading',
        value,
        identifier='EVOL',
        size_prefixed=size_prefixed,
        initial_size=initial_size,
    )


__all__ = ['Reading', 'ReadingView', 'build_reading']
