"""Generate msgspec models and lazy FlatBuffers views from reflected schemas."""

from __future__ import annotations

import keyword
import re
from collections import defaultdict
from collections.abc import Iterable, Sequence
from functools import lru_cache
from pathlib import Path
from typing import NamedTuple

import msgspec

from ._dynamic import (
    _MSGSPEC_TAG_FIELD,
    _OPAQUE_DATA_FIELD,
    dynamic_allow_prefix,
)
from .compiler import StrPath, compile_schema
from .schema import (
    BaseType,
    EnumDefinition,
    FieldDefinition,
    ObjectDefinition,
    Schema,
    TypeReference,
)

_GENERATED_HEADER = "# Generated by msgspec-flatbuffers. DO NOT EDIT."


class GenerationError(ValueError):
    """Raised when a schema cannot be represented by the current generator."""


class _ScalarSpec(NamedTuple):
    python_type: str
    runtime_name: str
    numpy_type: str
    size: int


class _UnionArm(NamedTuple):
    tag: int
    enum_name: str
    object: ObjectDefinition


class _UnionPair(NamedTuple):
    value_field: FieldDefinition
    type_field: FieldDefinition
    enum: EnumDefinition
    arms: tuple[_UnionArm, ...]
    vector: bool


class _DynamicPair(NamedTuple):
    value_field: FieldDefinition
    type_field: FieldDefinition
    allowed_prefix: str


def _hidden_type_field_ids(
    union_pairs: Sequence[_UnionPair],
    dynamic_pairs: Sequence[_DynamicPair],
) -> set[int]:
    return {pair.type_field.id for pair in union_pairs} | {
        pair.type_field.id for pair in dynamic_pairs
    }


_SCALARS: dict[BaseType, _ScalarSpec] = {
    BaseType.UTYPE: _ScalarSpec("int", "uint8", "np.uint8", 1),
    BaseType.BOOL: _ScalarSpec("bool", "bool", "np.bool_", 1),
    BaseType.BYTE: _ScalarSpec("int", "int8", "np.int8", 1),
    BaseType.UBYTE: _ScalarSpec("int", "uint8", "np.uint8", 1),
    BaseType.SHORT: _ScalarSpec("int", "int16", "np.int16", 2),
    BaseType.USHORT: _ScalarSpec("int", "uint16", "np.uint16", 2),
    BaseType.INT: _ScalarSpec("int", "int32", "np.int32", 4),
    BaseType.UINT: _ScalarSpec("int", "uint32", "np.uint32", 4),
    BaseType.LONG: _ScalarSpec("int", "int64", "np.int64", 8),
    BaseType.ULONG: _ScalarSpec("int", "uint64", "np.uint64", 8),
    BaseType.FLOAT: _ScalarSpec("float", "float32", "np.float32", 4),
    BaseType.DOUBLE: _ScalarSpec("float", "float64", "np.float64", 8),
}

_NUMPY_DTYPES: dict[BaseType, str] = {
    BaseType.UTYPE: "<u1",
    BaseType.BOOL: "?",
    BaseType.BYTE: "<i1",
    BaseType.UBYTE: "<u1",
    BaseType.SHORT: "<i2",
    BaseType.USHORT: "<u2",
    BaseType.INT: "<i4",
    BaseType.UINT: "<u4",
    BaseType.LONG: "<i8",
    BaseType.ULONG: "<u8",
    BaseType.FLOAT: "<f4",
    BaseType.DOUBLE: "<f8",
}

_SCALAR_READERS: dict[BaseType, tuple[str, str]] = {
    BaseType.UTYPE: ("_UINT8", "<B"),
    BaseType.BOOL: ("_BOOL", "<?"),
    BaseType.BYTE: ("_INT8", "<b"),
    BaseType.UBYTE: ("_UINT8", "<B"),
    BaseType.SHORT: ("_INT16", "<h"),
    BaseType.USHORT: ("_UINT16", "<H"),
    BaseType.INT: ("_INT32", "<i"),
    BaseType.UINT: ("_UINT32", "<I"),
    BaseType.LONG: ("_INT64", "<q"),
    BaseType.ULONG: ("_UINT64", "<Q"),
    BaseType.FLOAT: ("_FLOAT32", "<f"),
    BaseType.DOUBLE: ("_FLOAT64", "<d"),
}


def _is_byte_vector(type_ref: TypeReference) -> bool:
    return (
        type_ref.base_type is BaseType.VECTOR
        and type_ref.element is BaseType.UBYTE
        and type_ref.index < 0
    )


@lru_cache(maxsize=4096)
def _snake_case(value: str) -> str:
    value = re.sub(r"(?<=[a-z0-9])(?=[A-Z])", "_", value)
    value = re.sub(r"[^0-9A-Za-z_]", "_", value).lower()
    if value and value[0].isdigit():
        value = f"_{value}"
    return value or "generated"


@lru_cache(maxsize=4096)
def _identifier(value: str) -> str:
    value = re.sub(r"\W", "_", value)
    if value and value[0].isdigit():
        value = f"_{value}"
    if keyword.iskeyword(value):
        value = f"{value}_"
    return value


@lru_cache(maxsize=4096)
def _short_name(qualified_name: str) -> str:
    return _identifier(qualified_name.rsplit(".", 1)[-1])


@lru_cache(maxsize=4096)
def _namespace(qualified_name: str) -> tuple[str, ...]:
    parts = qualified_name.split(".")
    return tuple(parts[:-1])


def _declaration_path(declaration_file: str | None) -> str:
    if declaration_file is None:
        raise GenerationError("flatc did not record a declaration file")
    return declaration_file.removeprefix("//")


def _definition_module(
    qualified_name: str,
    declaration_file: str | None,
    package_prefix: tuple[str, ...],
) -> str:
    namespace = tuple(_snake_case(part) for part in _namespace(qualified_name))
    module = _snake_case(Path(_declaration_path(declaration_file)).stem)
    return ".".join((*package_prefix, *namespace, module))


@lru_cache(maxsize=1024)
def _field_order(item: ObjectDefinition) -> tuple[FieldDefinition, ...]:
    fields = [field for field in item.fields if not field.deprecated]
    key = (lambda field: field.offset) if item.is_struct else (lambda field: field.id)
    return tuple(sorted(fields, key=key))


class _Context:
    def __init__(
        self,
        schema: Schema,
        declaration_file: str,
        package_prefix: tuple[str, ...],
    ) -> None:
        self.schema = schema
        self.declaration_file = declaration_file
        self.package_prefix = package_prefix
        self._nested_targets: dict[
            tuple[str, int], ObjectDefinition | None
        ] = {}
        self._union_arms: dict[str, tuple[_UnionArm, ...]] = {}
        self._union_pairs: dict[str, tuple[_UnionPair, ...]] = {}
        self._dynamic_pairs: dict[str, tuple[_DynamicPair, ...]] = {}

    def object_for(self, type_ref: TypeReference) -> ObjectDefinition:
        if type_ref.index < 0 or type_ref.index >= len(self.schema.objects):
            raise GenerationError(f"invalid object type index {type_ref.index}")
        return self.schema.objects[type_ref.index]

    def enum_for(self, type_ref: TypeReference) -> EnumDefinition | None:
        if type_ref.index < 0:
            return None
        if type_ref.index >= len(self.schema.enums):
            raise GenerationError(f"invalid enum type index {type_ref.index}")
        return self.schema.enums[type_ref.index]

    def nested_target(
        self,
        owner: ObjectDefinition,
        field: FieldDefinition,
    ) -> ObjectDefinition | None:
        cache_key = (owner.name, field.id)
        if cache_key in self._nested_targets:
            return self._nested_targets[cache_key]
        target_name = field.nested_flatbuffer
        if target_name is None:
            self._nested_targets[cache_key] = None
            return None
        if not _is_byte_vector(field.type):
            raise GenerationError(
                f"nested_flatbuffer field {owner.name}.{field.name} "
                "must be a [ubyte] vector"
            )
        if "." in target_name:
            candidates = (target_name,)
        else:
            namespace = ".".join(_namespace(owner.name))
            candidates = (
                f"{namespace}.{target_name}" if namespace else target_name,
            )
        matches = [item for item in self.schema.objects if item.name in candidates]
        if len(matches) != 1:
            raise GenerationError(
                f"nested_flatbuffer target {target_name!r} for "
                f"{owner.name}.{field.name} was not found"
            )
        target = matches[0]
        if target.is_struct:
            raise GenerationError(
                f"nested_flatbuffer target {target.name} must be a table"
            )
        self._nested_targets[cache_key] = target
        return target

    def union_enum(self, type_ref: TypeReference) -> EnumDefinition:
        enum = self.enum_for(type_ref)
        if enum is None or not enum.is_union:
            raise GenerationError("union field does not reference a union enum")
        return enum

    def union_arms(self, enum: EnumDefinition) -> tuple[_UnionArm, ...]:
        cached = self._union_arms.get(enum.name)
        if cached is not None:
            return cached
        if enum.underlying_type.base_type is not BaseType.UTYPE:
            raise GenerationError(
                f"union {enum.name} must use the UTYPE discriminator"
            )
        none_values = [
            value
            for value in enum.values
            if value.union_type is not None
            and value.union_type.base_type is BaseType.NONE
        ]
        if len(none_values) != 1:
            raise GenerationError(
                f"union {enum.name} must define exactly one NONE alternative"
            )
        if none_values[0].value != 0:
            raise GenerationError(
                f"union {enum.name} NONE alternative must have tag 0"
            )
        seen_objects: set[int] = set()
        seen_tags = {0}
        arms: list[_UnionArm] = []
        for value in enum.values:
            union_type = value.union_type
            if union_type is None:
                raise GenerationError(
                    f"union alternative {enum.name}.{value.name} has no type"
                )
            if union_type.base_type is BaseType.NONE:
                continue
            if value.value < 1 or value.value > 255:
                raise GenerationError(
                    f"union alternative {enum.name}.{value.name} tag "
                    f"{value.value} is outside uint8 range"
                )
            if value.value in seen_tags:
                raise GenerationError(
                    f"union {enum.name} has duplicate discriminator tag "
                    f"{value.value}"
                )
            seen_tags.add(value.value)
            if union_type.base_type is not BaseType.OBJECT:
                raise GenerationError(
                    f"unsupported union alternative {enum.name}.{value.name}: "
                    f"{union_type.base_type.name.lower()}"
                )
            target = self.object_for(union_type)
            if target.is_struct:
                raise GenerationError(
                    f"unsupported union struct alternative "
                    f"{enum.name}.{value.name}"
                )
            if union_type.index in seen_objects:
                raise GenerationError(
                    f"union aliases are not supported: {enum.name}"
                )
            seen_objects.add(union_type.index)
            arms.append(_UnionArm(value.value, value.name, target))
        if not arms:
            raise GenerationError(f"union {enum.name} has no table alternatives")
        result = tuple(arms)
        self._union_arms[enum.name] = result
        return result

    def union_pairs(self, item: ObjectDefinition) -> tuple[_UnionPair, ...]:
        cached = self._union_pairs.get(item.name)
        if cached is not None:
            return cached
        if item.is_struct and any(
            field.type.base_type is BaseType.UNION
            or field.type.base_type is BaseType.VECTOR
            and field.type.element is BaseType.UNION
            for field in item.fields
        ):
            raise GenerationError(f"FlatBuffers struct {item.name} cannot contain unions")
        fields = _field_order(item)
        by_id = {field.id: field for field in fields}
        if len(by_id) != len(fields):
            raise GenerationError(f"object {item.name} has duplicate field ids")
        pairs: list[_UnionPair] = []
        paired_type_field_ids: set[int] = set()
        for value_field in fields:
            type_ref = value_field.type
            scalar_union = type_ref.base_type is BaseType.UNION
            vector_union = (
                type_ref.base_type is BaseType.VECTOR
                and type_ref.element is BaseType.UNION
            )
            if not scalar_union and not vector_union:
                continue
            enum = self.union_enum(type_ref)
            type_field = by_id.get(value_field.id - 1)
            expected_name = f"{value_field.name}_type"
            if type_field is None or type_field.name != expected_name:
                raise GenerationError(
                    f"union field {item.name}.{value_field.name} has no matching "
                    f"{expected_name!r} discriminator"
                )
            type_type = type_field.type
            valid_type = (
                type_type.base_type is BaseType.UTYPE
                if scalar_union
                else type_type.base_type is BaseType.VECTOR
                and type_type.element is BaseType.UTYPE
            )
            if not valid_type or type_type.index != type_ref.index:
                raise GenerationError(
                    f"union field {item.name}.{value_field.name} has a malformed "
                    "discriminator pair"
                )
            paired_type_field_ids.add(type_field.id)
            pairs.append(
                _UnionPair(
                    value_field,
                    type_field,
                    enum,
                    self.union_arms(enum),
                    vector_union,
                )
            )
        for field in fields:
            can_be_discriminator = (
                field.type.base_type is BaseType.UTYPE
                or field.type.base_type is BaseType.VECTOR
                and field.type.element is BaseType.UTYPE
            )
            if not can_be_discriminator:
                continue
            enum = self.enum_for(field.type)
            is_union_type = enum is not None and enum.is_union
            if is_union_type and field.id not in paired_type_field_ids:
                raise GenerationError(
                    f"orphan union discriminator {item.name}.{field.name}"
                )
        result = tuple(pairs)
        self._union_pairs[item.name] = result
        return result

    def dynamic_pairs(self, item: ObjectDefinition) -> tuple[_DynamicPair, ...]:
        cached = self._dynamic_pairs.get(item.name)
        if cached is not None:
            return cached
        fields = _field_order(item)
        by_name = {field.name: field for field in fields}
        pairs: list[_DynamicPair] = []
        paired_type_field_ids: set[int] = set()
        for value_field in fields:
            type_field_name = value_field.dynamic_flatbuffer
            if type_field_name is None:
                continue
            payload_name = f"{item.name}.{value_field.name}"
            if item.is_struct:
                raise GenerationError(
                    f"FlatBuffers struct {item.name} cannot contain dynamic fields"
                )
            if not _is_byte_vector(value_field.type):
                raise GenerationError(
                    f"dynamic_flatbuffer field {payload_name} must be a "
                    "[ubyte] vector"
                )
            if value_field.nested_flatbuffer is not None:
                raise GenerationError(
                    f"field {payload_name} cannot use both "
                    "dynamic_flatbuffer and nested_flatbuffer"
                )
            allow_pattern = value_field.dynamic_allow
            if allow_pattern is None:
                raise GenerationError(
                    f"dynamic_flatbuffer field {payload_name} "
                    "requires dynamic_allow"
                )
            try:
                allowed_prefix = dynamic_allow_prefix(allow_pattern)
            except ValueError as error:
                raise GenerationError(
                    f"invalid dynamic_allow on {payload_name}: {error}"
                ) from error
            type_field = by_name.get(type_field_name)
            if type_field is None:
                raise GenerationError(
                    f"dynamic_flatbuffer field {payload_name} "
                    f"references missing type field {type_field_name!r}"
                )
            qualified_type_field_name = f"{item.name}.{type_field.name}"
            if (
                type_field.id == value_field.id
                or type_field.id in paired_type_field_ids
            ):
                raise GenerationError(
                    f"dynamic FlatBuffer type field {qualified_type_field_name} "
                    "must belong to exactly one payload"
                )
            if (
                type_field.type.base_type is not BaseType.STRING
                or type_field.required != value_field.required
            ):
                raise GenerationError(
                    f"dynamic FlatBuffer type field {qualified_type_field_name} "
                    "must be a string with matching requiredness"
                )
            paired_type_field_ids.add(type_field.id)
            pairs.append(_DynamicPair(value_field, type_field, allowed_prefix))
        for field in fields:
            if field.dynamic_allow is not None and field.dynamic_flatbuffer is None:
                raise GenerationError(
                    f"field {item.name}.{field.name} uses dynamic_allow without "
                    "dynamic_flatbuffer"
                )
        result = tuple(pairs)
        self._dynamic_pairs[item.name] = result
        return result

    def scalar_spec(self, base_type: BaseType) -> _ScalarSpec:
        try:
            return _SCALARS[base_type]
        except KeyError as error:
            raise GenerationError(f"unsupported scalar type {base_type.name}") from error

    def scalar_python_type(self, type_ref: TypeReference) -> str:
        enum = self.enum_for(type_ref)
        if enum is not None:
            return _short_name(enum.name)
        return self.scalar_spec(type_ref.base_type).python_type

    def model_type(self, type_ref: TypeReference) -> str:
        if type_ref.base_type in _SCALARS:
            return self.scalar_python_type(type_ref)
        if type_ref.base_type is BaseType.STRING:
            return "str"
        if type_ref.base_type is BaseType.OBJECT:
            return _short_name(self.object_for(type_ref).name)
        if type_ref.base_type is BaseType.VECTOR:
            return self.vector_model_type(type_ref)
        raise GenerationError(f"unsupported model type {type_ref.base_type.name}")

    def vector_model_type(self, type_ref: TypeReference) -> str:
        element = type_ref.element
        if _is_byte_vector(type_ref):
            return "bytes"
        if element in _SCALARS:
            enum = self.enum_for(type_ref)
            if enum is not None:
                return f"list[{_short_name(enum.name)}]"
            return f"npt.NDArray[{self.scalar_spec(element).numpy_type}]"
        if element is BaseType.STRING:
            return "list[str]"
        if element is BaseType.OBJECT:
            return f"list[{_short_name(self.object_for(type_ref).name)}]"
        raise GenerationError(f"unsupported vector element type {element.name}")

    def view_type(self, type_ref: TypeReference) -> str:
        if type_ref.base_type in _SCALARS:
            return self.scalar_python_type(type_ref)
        if type_ref.base_type is BaseType.STRING:
            return "str"
        if type_ref.base_type is BaseType.OBJECT:
            return f"{_short_name(self.object_for(type_ref).name)}View"
        if type_ref.base_type is BaseType.VECTOR:
            return self.vector_view_type(type_ref)
        raise GenerationError(f"unsupported view type {type_ref.base_type.name}")

    def vector_view_type(self, type_ref: TypeReference) -> str:
        element = type_ref.element
        if _is_byte_vector(type_ref):
            return "memoryview"
        if element in _SCALARS:
            dtype = self.scalar_spec(element).numpy_type
            return f"npt.NDArray[{dtype}]"
        if element is BaseType.STRING:
            return "StringVector"
        if element is BaseType.OBJECT:
            item = self.object_for(type_ref)
            wrapper = "StructVector" if item.is_struct else "TableVector"
            return f"{wrapper}[{_short_name(item.name)}View]"
        raise GenerationError(f"unsupported vector element type {element.name}")

    def default_expression(self, field: FieldDefinition) -> str:
        if field.optional:
            return "None"
        enum = self.enum_for(field.type)
        if enum is not None:
            return f"{_short_name(enum.name)}({field.default_integer})"
        if field.type.base_type is BaseType.BOOL:
            return repr(bool(field.default_integer))
        if field.type.base_type in (BaseType.FLOAT, BaseType.DOUBLE):
            return _float_literal(field.default_real)
        return repr(field.default_integer)

    def referenced_definitions(
        self,
        local_objects: list[ObjectDefinition],
        local_enums: list[EnumDefinition],
    ) -> tuple[dict[str, set[str]], dict[str, set[str]]]:
        objects: dict[str, set[str]] = defaultdict(set)
        enums: dict[str, set[str]] = defaultdict(set)
        for item in local_objects:
            self.dynamic_pairs(item)
            for field in item.fields:
                nested = self.nested_target(item, field)
                if nested is not None:
                    self._record_nested_object(objects, nested)
                type_ref = field.type
                if type_ref.base_type is BaseType.OBJECT:
                    self._record_object(objects, self.object_for(type_ref))
                elif type_ref.base_type is BaseType.VECTOR:
                    if type_ref.element is BaseType.OBJECT:
                        self._record_object(objects, self.object_for(type_ref))
                    elif type_ref.element in _SCALARS:
                        enum = self.enum_for(type_ref)
                        if enum is not None:
                            self._record_enum(enums, enum)
                elif type_ref.base_type in _SCALARS:
                    enum = self.enum_for(type_ref)
                    if enum is not None:
                        self._record_enum(enums, enum)
            for pair in self.union_pairs(item):
                self._record_enum(enums, pair.enum)
                for arm in pair.arms:
                    self._record_object(objects, arm.object)
        for enum in local_enums:
            if enum.is_union:
                for arm in self.union_arms(enum):
                    self._record_object(objects, arm.object)
        return objects, enums

    def _record_nested_object(
        self,
        imports: dict[str, set[str]],
        item: ObjectDefinition,
    ) -> None:
        if item.declaration_file == self.declaration_file:
            return
        module = _definition_module(
            item.name,
            item.declaration_file,
            self.package_prefix,
        )
        name = _short_name(item.name)
        imports[module].update((name, f"{name}View"))

    def _record_object(
        self,
        imports: dict[str, set[str]],
        item: ObjectDefinition,
    ) -> None:
        if item.declaration_file == self.declaration_file:
            return
        module = _definition_module(
            item.name,
            item.declaration_file,
            self.package_prefix,
        )
        name = _short_name(item.name)
        imports[module].update((name, f"{name}View"))

    def _record_enum(
        self,
        imports: dict[str, set[str]],
        item: EnumDefinition,
    ) -> None:
        if item.declaration_file == self.declaration_file:
            return
        module = _definition_module(
            item.name,
            item.declaration_file,
            self.package_prefix,
        )
        imports[module].add(_short_name(item.name))
        if item.is_union:
            imports[module].add(f"_FB_UNION_{_short_name(item.name)}")


def _float_literal(value: float) -> str:
    if value != value:
        return 'float("nan")'
    if value == float("inf"):
        return 'float("inf")'
    if value == float("-inf"):
        return 'float("-inf")'
    return repr(value)


def _documentation(lines: tuple[str, ...], indent: str = "    ") -> list[str]:
    if not lines:
        return []
    text = "\n".join(lines)
    return [f"{indent}{text!r}"]


def _has_marker_attribute(item: ObjectDefinition, key: str) -> bool:
    matches = [attribute for attribute in item.attributes if attribute.key == key]
    if len(matches) > 1:
        raise GenerationError(f"table {item.name} has duplicate {key!r} attributes")
    if not matches:
        return False
    if matches[0].value not in (None, "0"):
        raise GenerationError(f"table {item.name} attribute {key!r} takes no value")
    return True


def _union_model_type(pair: _UnionPair) -> str:
    return " | ".join(_short_name(arm.object.name) for arm in pair.arms)


def _union_view_type(pair: _UnionPair) -> str:
    return " | ".join(f"{_short_name(arm.object.name)}View" for arm in pair.arms)


def _dynamic_value_type_name(
    owner: ObjectDefinition,
    pair: _DynamicPair,
) -> str:
    return (
        f"_Dynamic_{_short_name(owner.name)}_"
        f"{_identifier(pair.value_field.name)}"
    )


def _render_dynamic_value_type(
    owner: ObjectDefinition,
    pair: _DynamicPair,
) -> list[str]:
    return [
        f"class {_dynamic_value_type_name(owner, pair)}(DynamicValue):",
        "    __slots__ = ()",
        f"    _allowed_prefix = {pair.allowed_prefix!r}",
    ]


def _model_field_line(
    context: _Context,
    owner: ObjectDefinition,
    field: FieldDefinition,
    union_pair: _UnionPair | None,
    dynamic_pair: _DynamicPair | None,
) -> str:
    name = _identifier(field.name)
    nested = context.nested_target(owner, field)
    if dynamic_pair is not None:
        annotation = _dynamic_value_type_name(owner, dynamic_pair)
    elif union_pair is not None:
        annotation = (
            f"list[{_union_model_type(union_pair)}]"
            if union_pair.vector
            else _union_model_type(union_pair)
        )
    elif nested is not None:
        annotation = _short_name(nested.name)
    else:
        annotation = context.model_type(field.type)
    if owner.is_struct:
        return f"    {name}: {annotation}"
    if field.type.base_type in _SCALARS:
        if field.optional:
            return f"    {name}: {annotation} | None = None"
        return f"    {name}: {annotation} = {context.default_expression(field)}"
    if field.required:
        return f"    {name}: {annotation}"
    return f"    {name}: {annotation} | None = None"


def _render_enum(context: _Context, item: EnumDefinition) -> list[str]:
    if item.is_union:
        context.union_arms(item)
    name = _short_name(item.name)
    lines = [f"class {name}(OpenIntEnum):"]
    lines.extend(_documentation(item.documentation))
    if not item.values:
        lines.append("    pass")
    else:
        for value in item.values:
            lines.append(f"    {_identifier(value.name)} = {value.value}")
    return lines


def _is_numeric_model_vector(context: _Context, field: FieldDefinition) -> bool:
    type_ref = field.type
    return (
        type_ref.base_type is BaseType.VECTOR
        and type_ref.element in _SCALARS
        and not _is_byte_vector(type_ref)
        and context.enum_for(type_ref) is None
    )


def _render_model_equality(
    context: _Context,
    item: ObjectDefinition,
    fields: Sequence[FieldDefinition],
) -> list[str]:
    name = _short_name(item.name)
    lines = [
        "    def __eq__(self, other: object) -> bool:",
        f"        if type(other) is not {name}:",
        "            return False",
        "        return (",
    ]
    comparisons: list[str] = []
    for field in fields:
        property_name = _identifier(field.name)
        if _is_numeric_model_vector(context, field):
            arrays_equal = (
                f"self.{property_name}.dtype == other.{property_name}.dtype and "
                f"np.array_equal(self.{property_name}, other.{property_name})"
            )
            comparison = (
                arrays_equal
                if field.required
                else (
                    f"(self.{property_name} is None and "
                    f"other.{property_name} is None) or "
                    f"(self.{property_name} is not None and "
                    f"other.{property_name} is not None and {arrays_equal})"
                )
            )
        else:
            comparison = f"self.{property_name} == other.{property_name}"
        comparisons.append(comparison)
    lines.append(f"            ({comparisons[0]})")
    lines.extend(f"            and ({comparison})" for comparison in comparisons[1:])
    lines.extend(
        [
            "        )",
            "",
            "    def __ne__(self, other: object) -> bool:",
            "        return not self == other",
        ]
    )
    return lines


def _render_union_dispatch(context: _Context, item: EnumDefinition) -> list[str]:
    arms = context.union_arms(item)
    none_value = next(
        value
        for value in item.values
        if value.union_type is not None
        and value.union_type.base_type is BaseType.NONE
    )
    lines = [
        f"_FB_UNION_{_short_name(item.name)} = UnionDispatch(",
        f"    {item.name!r},",
        f"    {none_value.value},",
        "    {",
    ]
    for arm in arms:
        lines.append(
            f"        {arm.tag}: {_short_name(arm.object.name)}View,"
        )
    lines.extend(("    },", ")"))
    return lines


def _render_model(
    context: _Context,
    item: ObjectDefinition,
    root: bool,
) -> list[str]:
    name = _short_name(item.name)
    fields = _field_order(item)
    union_pairs = context.union_pairs(item)
    union_pairs_by_value_id = {
        pair.value_field.id: pair for pair in union_pairs
    }
    dynamic_pairs = context.dynamic_pairs(item)
    dynamic_pairs_by_value_id = {
        pair.value_field.id: pair for pair in dynamic_pairs
    }
    hidden_type_field_ids = _hidden_type_field_ids(union_pairs, dynamic_pairs)
    model_fields = [
        field for field in fields if field.id not in hidden_type_field_ids
    ]
    has_numeric_vectors = any(
        _is_numeric_model_vector(context, field) for field in model_fields
    )
    options = ["frozen=True", "kw_only=True"]
    if not item.is_struct:
        reserved_fields = {
            _MSGSPEC_TAG_FIELD,
            _OPAQUE_DATA_FIELD,
        }
        conflict = next(
            (
                _identifier(field.name)
                for field in fields
                if _identifier(field.name) in reserved_fields
            ),
            None,
        )
        if conflict is not None:
            description = (
                "msgspec tag field"
                if conflict == _MSGSPEC_TAG_FIELD
                else "dynamic payload field"
            )
            raise GenerationError(
                f"table {item.name} uses reserved {description} {conflict!r}"
            )
        options.extend(
            (
                f"tag={item.name!r}",
                f"tag_field={_MSGSPEC_TAG_FIELD!r}",
            )
        )
    if has_numeric_vectors:
        options.append("eq=False")
    lines = [f"class {name}(msgspec.Struct, {', '.join(options)}):"]
    lines.extend(_documentation(item.documentation))
    if not model_fields:
        lines.append("    pass")
    for field in model_fields:
        lines.append(
            _model_field_line(
                context,
                item,
                field,
                union_pairs_by_value_id.get(field.id),
                dynamic_pairs_by_value_id.get(field.id),
            )
        )
    if has_numeric_vectors:
        lines.append("")
        lines.extend(_render_model_equality(context, item, model_fields))
    if not item.is_struct:
        if model_fields or has_numeric_vectors:
            lines.append("")
        identifier = (
            repr(context.schema.file_identifier)
            if root and context.schema.file_identifier is not None
            else "None"
        )
        lines.extend(
            [
                "    def to_flatbuffer(",
                "        self,",
                "        *,",
                "        size_prefixed: bool = False,",
                "        initial_size: int = 0,",
                "    ) -> memoryview:",
                "        return _FB_NATIVE_MODULE.pack(",
                f"            {item.name!r},",
                "            self,",
                f"            identifier={identifier},",
                "            size_prefixed=size_prefixed,",
                "            initial_size=initial_size,",
                "        )",
            ]
        )
    return lines


def _scalar_view_property(
    context: _Context,
    field: FieldDefinition,
    struct: bool,
) -> list[str]:
    name = _identifier(field.name)
    annotation = context.scalar_python_type(field.type)
    if field.optional and not struct:
        annotation = f"{annotation} | None"
    body = _scalar_load_lines(
        context,
        field,
        struct=struct,
        target="value",
        indent="        ",
    )
    return [
        "    @property",
        f"    def {name}(self) -> {annotation}:",
        *body,
        "        return value",
    ]


def _scalar_load_lines(
    context: _Context,
    field: FieldDefinition,
    *,
    struct: bool,
    target: str,
    indent: str,
    use_table_locals: bool = False,
) -> list[str]:
    """Render one checked scalar load without generic runtime dispatch."""

    scalar = context.scalar_spec(field.type.base_type)
    reader, _ = _SCALAR_READERS[field.type.base_type]
    enum = context.enum_for(field.type)
    present = f"{reader}.unpack_from({{buffer}}, {{position}})[0]"
    if enum is not None:
        present = f"{_short_name(enum.name)}({present})"

    if struct:
        return [
            f"{indent}{target} = "
            + present.format(
                buffer="self._buffer",
                position=f"self._struct_offset + {field.offset}",
            )
        ]

    if field.offset < 4 or field.offset % 2:
        raise GenerationError(
            f"invalid vtable offset {field.offset} for scalar field {field.name!r}"
        )

    default = context.default_expression(field)
    buffer = "_fb_buffer" if use_table_locals else "self._buffer"
    vtable_size = "_fb_vtable_size" if use_table_locals else "self._vtable_size"
    vtable_offset = (
        "_fb_vtable_offset" if use_table_locals else "self._vtable_offset"
    )
    object_size = "_fb_object_size" if use_table_locals else "self._object_size"
    table_offset = "_fb_table_offset" if use_table_locals else "self._table_offset"
    relative = f"{target}_relative"
    return [
        f"{indent}if {field.offset} >= {vtable_size}:",
        f"{indent}    {target} = {default}",
        f"{indent}else:",
        f"{indent}    {relative} = _UINT16.unpack_from("
        f"{buffer}, {vtable_offset} + {field.offset})[0]",
        f"{indent}    if {relative} == 0:",
        f"{indent}        {target} = {default}",
        f"{indent}    elif {relative} < 4 or "
        f"{relative} > {object_size} - {scalar.size}:",
        f"{indent}        raise InvalidBufferError("
        '"field lies outside its FlatBuffers table")',
        f"{indent}    else:",
        f"{indent}        {target} = "
        + present.format(
            buffer=buffer,
            position=f"{table_offset} + {relative}",
        ),
    ]


def _cache_slot(field: FieldDefinition) -> str:
    return f"_fb_cached_{_identifier(field.name)}"


def _struct_unpacker(
    context: _Context,
    item: ObjectDefinition,
) -> tuple[str, str] | None:
    """Return a composite unpacker name/format for a scalar-only struct."""

    if not item.is_struct:
        return None
    fields = _field_order(item)
    if not fields or any(field.type.base_type not in _SCALARS for field in fields):
        return None

    parts = ["<"]
    cursor = 0
    for field in fields:
        scalar = context.scalar_spec(field.type.base_type)
        if field.offset < cursor:
            raise GenerationError(f"overlapping struct field {field.name!r}")
        padding = field.offset - cursor
        if padding:
            parts.append("x" if padding == 1 else f"{padding}x")
        _, scalar_format = _SCALAR_READERS[field.type.base_type]
        parts.append(scalar_format.removeprefix("<"))
        cursor = field.offset + scalar.size
    if item.byte_size < cursor:
        raise GenerationError(f"struct {item.name!r} fields exceed its byte size")
    return f"_FB_UNPACK_{_short_name(item.name)}", "".join(parts)


def _complex_view_loader(context: _Context, field: FieldDefinition) -> str:
    type_ref = field.type
    if type_ref.base_type is BaseType.STRING:
        return f"self._read_string({field.offset})"
    if type_ref.base_type is BaseType.OBJECT:
        item = context.object_for(type_ref)
        method = "_read_struct" if item.is_struct else "_read_table"
        return f"self.{method}({field.offset}, {_short_name(item.name)}View)"
    if type_ref.base_type is BaseType.VECTOR:
        element = type_ref.element
        if _is_byte_vector(type_ref):
            return f"self._read_byte_vector({field.offset})"
        if element in _SCALARS:
            dtype = _NUMPY_DTYPES[element]
            return f"self._read_numpy_vector({field.offset}, {dtype!r})"
        if element is BaseType.STRING:
            return f"self._read_string_vector({field.offset})"
        if element is BaseType.OBJECT:
            item = context.object_for(type_ref)
            method = "_read_struct_vector" if item.is_struct else "_read_table_vector"
            return f"self.{method}({field.offset}, {_short_name(item.name)}View)"
        raise GenerationError(f"unsupported vector element type {element.name}")
    raise GenerationError(f"unsupported field type {type_ref.base_type.name}")


def _complex_cache_load_lines(
    context: _Context,
    field: FieldDefinition,
    *,
    target: str,
    indent: str,
) -> list[str]:
    """Render a direct per-field slot cache lookup and cold-path load."""

    slot = _cache_slot(field)
    lines = [
        f"{indent}try:",
        f"{indent}    {target} = self.{slot}",
        f"{indent}except AttributeError:",
        f"{indent}    {target} = {_complex_view_loader(context, field)}",
    ]
    if field.required:
        lines.extend(
            [
                f"{indent}    if {target} is None:",
                f"{indent}        raise InvalidBufferError("
                f"\"required field {field.name!r} is absent\")",
            ]
        )
    lines.append(f"{indent}    self.{slot} = {target}")
    return lines


def _complex_view_property(context: _Context, field: FieldDefinition) -> list[str]:
    name = _identifier(field.name)
    annotation = context.view_type(field.type)
    return_type = annotation if field.required else f"{annotation} | None"
    lines = [
        "    @property",
        f"    def {name}(self) -> {return_type}:",
        *_complex_cache_load_lines(
            context,
            field,
            target="value",
            indent="        ",
        ),
        "        return value",
    ]
    return lines


def _byte_vector_as_method(field: FieldDefinition) -> list[str]:
    property_name = _identifier(field.name)
    return_type = "_NestedViewT" if field.required else "_NestedViewT | None"
    cache_key = f"_fb_nested_views:{property_name}"
    lines = [
        f"    def {property_name}_as(",
        "        self,",
        "        view_type: type[_NestedViewT],",
        "        *,",
        "        size_prefixed: bool = False,",
        f"    ) -> {return_type}:",
        f"        payload = self.{property_name}",
    ]
    if not field.required:
        lines.extend(
            [
                "        if payload is None:",
                "            return None",
            ]
        )
    lines.extend(
        [
            "        try:",
            "            cache: dict[tuple[type[TableView], bool], Any] = (",
            f"                self._cache[{cache_key!r}]",
            "            )",
            "        except KeyError:",
            "            cache = {}",
            f"            self._cache[{cache_key!r}] = cache",
            "        key = (view_type, size_prefixed)",
            "        try:",
            "            return cache[key]",
            "        except KeyError:",
            "            value = view_type.from_buffer(",
            "                payload,",
            "                size_prefixed=size_prefixed,",
            "            )",
            "            cache[key] = value",
            "            return value",
        ]
    )
    return lines


def _nested_cache_slot(field: FieldDefinition) -> str:
    return f"_fb_nested_{_identifier(field.name)}"


def _dynamic_cache_slot(field: FieldDefinition) -> str:
    return f"_fb_dynamic_{_identifier(field.name)}"


def _dynamic_view_method(
    owner: ObjectDefinition,
    pair: _DynamicPair,
) -> list[str]:
    field = pair.value_field
    property_name = _identifier(field.name)
    type_property = _identifier(pair.type_field.name)
    cache_slot = _dynamic_cache_slot(field)
    value_type = _dynamic_value_type_name(owner, pair)
    return_type = "DynamicView" if field.required else "DynamicView | None"
    lines = [
        f"    def {property_name}_dynamic(self) -> {return_type}:",
        "        try:",
        f"            return self.{cache_slot}",
        "        except AttributeError:",
        f"            type_tag = self.{type_property}",
        f"            payload = self.{property_name}",
        "            if type_tag is None:",
        "                if payload is not None:",
        "                    raise InvalidBufferError(",
        f"                        \"dynamic field {field.name!r} has data "
        "without a type tag\"",
        "                    )",
    ]
    if field.required:
        lines.extend(
            [
                "                raise InvalidBufferError(",
                f"                    \"required dynamic field {field.name!r} "
                "is absent\"",
                "                )",
            ]
        )
    else:
        lines.append("                value = None")
    lines.extend(
        [
            "            elif payload is None:",
            "                raise InvalidBufferError(",
            f"                    \"dynamic field {field.name!r} type tag "
            "has no data\"",
            "                )",
            "            else:",
            "                value = DynamicView(",
            f"                    type_tag, payload, {value_type}",
            "                )",
            f"            self.{cache_slot} = value",
            "            return value",
        ]
    )
    return lines


def _nested_view_method(
    field: FieldDefinition,
    target: ObjectDefinition,
) -> list[str]:
    property_name = _identifier(field.name)
    target_name = _short_name(target.name)
    return_type = f"{target_name}View" if field.required else f"{target_name}View | None"
    cache_slot = _nested_cache_slot(field)
    lines = [
        f"    def {property_name}_view(",
        "        self,",
        "        *,",
        "        size_prefixed: bool = False,",
        f"    ) -> {return_type}:",
        f"        payload = self.{property_name}",
    ]
    if not field.required:
        lines.extend(
            [
                "        if payload is None:",
                "            return None",
            ]
        )
    lines.extend(
        [
            "        try:",
            f"            cache: dict[bool, {target_name}View] = self.{cache_slot}",
            "        except AttributeError:",
            "            cache = {}",
            f"            self.{cache_slot} = cache",
            "        try:",
            "            return cache[size_prefixed]",
            "        except KeyError:",
            f"            value = {target_name}View.from_buffer(",
            "                payload,",
            "                size_prefixed=size_prefixed,",
            "            )",
            "            cache[size_prefixed] = value",
            "            return value",
        ]
    )
    return lines


def _union_cache_load_lines(
    pair: _UnionPair,
    *,
    target: str,
    indent: str,
) -> list[str]:
    field = pair.value_field
    slot = _cache_slot(field)
    property_name = _identifier(field.name)
    dispatch = f"_FB_UNION_{_short_name(pair.enum.name)}"
    annotation = _union_view_type(pair)
    if not field.required:
        annotation = f"{annotation} | None"
    lines = [
        f"{indent}try:",
        f"{indent}    {target} = self.{slot}",
        f"{indent}except AttributeError:",
        f"{indent}    {target} = cast(",
        f"{indent}        {annotation},",
        f"{indent}        self._read_union(",
        f"{indent}            {field.offset}, int(self.{property_name}_type), {dispatch}",
        f"{indent}        ),",
        f"{indent}    )",
    ]
    if field.required:
        lines.extend(
            [
                f"{indent}    if {target} is None:",
                f"{indent}        raise InvalidBufferError("
                f"\"required field {field.name!r} is absent\")",
            ]
        )
    lines.append(f"{indent}    self.{slot} = {target}")
    return lines


def _union_view_method(pair: _UnionPair) -> list[str]:
    field = pair.value_field
    property_name = _identifier(field.name)
    annotation = _union_view_type(pair)
    if not field.required:
        annotation = f"{annotation} | None"
    return [
        f"    def {property_name}_view(self) -> {annotation}:",
        *_union_cache_load_lines(
            pair,
            target="value",
            indent="        ",
        ),
        "        return value",
    ]


def _union_vector_cache_load_lines(
    pair: _UnionPair,
    *,
    target: str,
    indent: str,
) -> list[str]:
    field = pair.value_field
    type_field = pair.type_field
    slot = _cache_slot(field)
    property_name = _identifier(field.name)
    type_property = _identifier(type_field.name)
    dispatch = f"_FB_UNION_{_short_name(pair.enum.name)}"
    reader, _ = _SCALAR_READERS[pair.enum.underlying_type.base_type]
    lines = [
        f"{indent}try:",
        f"{indent}    {target} = self.{slot}",
        f"{indent}except AttributeError:",
        f"{indent}    types = self.{type_property}",
        f"{indent}    info = self._vector_info({field.offset}, 4)",
        f"{indent}    if types is None and info is None:",
    ]
    if field.required:
        lines.append(
            f"{indent}        raise InvalidBufferError("
            f"\"required field {field.name!r} is absent\")"
        )
    else:
        lines.append(f"{indent}        {target} = None")
    lines.extend(
        [
            f"{indent}    elif types is None or info is None:",
            f"{indent}        raise InvalidBufferError("
            f"\"union vector {field.name!r} type/value presence differs\")",
            f"{indent}    else:",
            f"{indent}        start, length = info",
            f"{indent}        {target} = UnionVector(",
            f"{indent}            self._buffer, types, start, length, {reader}, {dispatch}",
            f"{indent}        )",
            f"{indent}    self.{slot} = {target}",
        ]
    )
    return lines


def _union_vector_property(pair: _UnionPair) -> list[str]:
    field = pair.value_field
    name = _identifier(field.name)
    annotation = f"UnionVector[{_union_view_type(pair)}]"
    if not field.required:
        annotation = f"{annotation} | None"
    return [
        "    @property",
        f"    def {name}(self) -> {annotation}:",
        *_union_vector_cache_load_lines(
            pair,
            target="value",
            indent="        ",
        ),
        "        return value",
    ]


def _model_conversion_expression(
    context: _Context,
    field: FieldDefinition,
    local: str,
) -> str:
    type_ref = field.type
    if type_ref.base_type is BaseType.STRING:
        expression = local
    elif type_ref.base_type is BaseType.OBJECT:
        expression = f"{local}.to_model()"
    elif type_ref.base_type is BaseType.VECTOR:
        element = type_ref.element
        if _is_byte_vector(type_ref):
            expression = f"bytes({local})"
        elif element in _SCALARS:
            enum = context.enum_for(type_ref)
            if enum is None:
                expression = (
                    f"np.array({local}, dtype="
                    f"{context.scalar_spec(element).numpy_type}, copy=True)"
                )
            else:
                enum_name = _short_name(enum.name)
                expression = f"list(map({enum_name}, {local}.tolist()))"
        elif element is BaseType.STRING:
            expression = f"list({local})"
        elif element is BaseType.OBJECT:
            item_name = _short_name(context.object_for(type_ref).name)
            expression = f"list(map({item_name}View.to_model, {local}))"
        else:
            raise GenerationError(f"unsupported vector element type {element.name}")
    else:
        raise GenerationError(f"unsupported complex type {type_ref.base_type.name}")

    if field.required:
        return expression
    return f"None if {local} is None else {expression}"


def _render_view(context: _Context, item: ObjectDefinition, root: bool) -> list[str]:
    name = _short_name(item.name)
    base = "StructView" if item.is_struct else "TableView"
    fields = _field_order(item)
    union_pairs = context.union_pairs(item)
    union_pairs_by_value_id = {
        pair.value_field.id: pair for pair in union_pairs
    }
    dynamic_pairs = context.dynamic_pairs(item)
    dynamic_pairs_by_value_id = {
        pair.value_field.id: pair for pair in dynamic_pairs
    }
    hidden_type_field_ids = _hidden_type_field_ids(union_pairs, dynamic_pairs)
    nested_targets = {
        field.id: target
        for field in fields
        if (target := context.nested_target(item, field)) is not None
    }
    cached_fields = [
        field for field in fields if field.type.base_type not in _SCALARS
    ]
    byte_vector_fields = [
        field
        for field in fields
        if _is_byte_vector(field.type)
        and field.id not in nested_targets
        and field.id not in dynamic_pairs_by_value_id
    ]
    property_names = {_identifier(field.name) for field in fields}
    for field in byte_vector_fields:
        method_name = f"{_identifier(field.name)}_as"
        if method_name in property_names:
            raise GenerationError(
                f"generated byte-vector helper {method_name!r} conflicts with a field"
            )
    for field in fields:
        if field.id in nested_targets:
            method_name = f"{_identifier(field.name)}_view"
            if method_name in property_names:
                raise GenerationError(
                    f"generated nested helper {method_name!r} conflicts with a field"
                )
        pair = union_pairs_by_value_id.get(field.id)
        if pair is not None and not pair.vector:
            method_name = f"{_identifier(field.name)}_view"
            if method_name in property_names:
                raise GenerationError(
                    f"generated union helper {method_name!r} conflicts with a field"
                )
        dynamic_pair = dynamic_pairs_by_value_id.get(field.id)
        if dynamic_pair is not None:
            method_name = f"{_identifier(field.name)}_dynamic"
            if method_name in property_names:
                raise GenerationError(
                    f"generated dynamic helper {method_name!r} conflicts with a field"
                )
    cache_slots = tuple(
        [*(_cache_slot(field) for field in cached_fields)]
        + [
            _nested_cache_slot(field)
            for field in fields
            if field.id in nested_targets
        ]
        + [
            _dynamic_cache_slot(pair.value_field)
            for pair in dynamic_pairs
        ]
    )
    lines = [f"class {name}View({base}):"]
    lines.extend(_documentation(item.documentation))
    lines.append(f"    __slots__ = {cache_slots!r}")
    if item.is_struct:
        lines.append(f"    __flatbuffer_size__ = {item.byte_size}")
    elif root and context.schema.file_identifier is not None:
        lines.append(
            f"    __flatbuffer_identifier__ = {context.schema.file_identifier.encode()!r}"
        )

    for field in fields:
        lines.append("")
        pair = union_pairs_by_value_id.get(field.id)
        if pair is not None:
            if pair.vector:
                lines.extend(_union_vector_property(pair))
            else:
                lines.extend(_union_view_method(pair))
        elif field.type.base_type in _SCALARS:
            lines.extend(_scalar_view_property(context, field, item.is_struct))
        elif item.is_struct:
            if field.type.base_type is not BaseType.OBJECT:
                raise GenerationError(
                    f"unsupported struct field type {field.type.base_type.name}"
                )
            nested = context.object_for(field.type)
            if not nested.is_struct:
                raise GenerationError("FlatBuffers structs may only contain structs")
            property_name = _identifier(field.name)
            nested_name = _short_name(nested.name)
            lines.extend(
                [
                    "    @property",
                    f"    def {property_name}(self) -> {nested_name}View:",
                    *_complex_cache_load_lines(
                        context,
                        field,
                        target="value",
                        indent="        ",
                    ),
                    "        return value",
                ]
            )
        else:
            lines.extend(_complex_view_property(context, field))

    for field in byte_vector_fields:
        lines.append("")
        lines.extend(_byte_vector_as_method(field))

    for field in fields:
        target = nested_targets.get(field.id)
        if target is not None:
            lines.append("")
            lines.extend(_nested_view_method(field, target))

    for pair in dynamic_pairs:
        lines.append("")
        lines.extend(_dynamic_view_method(item, pair))

    if fields:
        lines.append("")
    lines.append(f"    def to_model(self) -> {name}:")
    model_fields = [
        field for field in fields if field.id not in hidden_type_field_ids
    ]
    scalar_fields = [
        field for field in model_fields if field.type.base_type in _SCALARS
    ]
    unpacker = _struct_unpacker(context, item)
    if unpacker is not None:
        unpacker_name, _ = unpacker
        targets = ", ".join(
            f"_{_identifier(field.name)}" for field in scalar_fields
        )
        if len(scalar_fields) == 1:
            targets += ","
        lines.append(
            f"        {targets} = {unpacker_name}.unpack_from("
            "self._buffer, self._struct_offset)"
        )
        for field in scalar_fields:
            enum = context.enum_for(field.type)
            if enum is not None:
                local = f"_{_identifier(field.name)}"
                lines.append(f"        {local} = {_short_name(enum.name)}({local})")
    use_table_locals = not item.is_struct and len(scalar_fields) > 1
    if use_table_locals:
        lines.extend(
            [
                "        _fb_buffer = self._buffer",
                "        _fb_vtable_size = self._vtable_size",
                "        _fb_vtable_offset = self._vtable_offset",
                "        _fb_object_size = self._object_size",
                "        _fb_table_offset = self._table_offset",
            ]
        )
    for field in model_fields:
        property_name = _identifier(field.name)
        local = f"_{property_name}"
        pair = union_pairs_by_value_id.get(field.id)
        dynamic_pair = dynamic_pairs_by_value_id.get(field.id)
        if dynamic_pair is not None:
            lines.append(f"        {local} = self.{property_name}_dynamic()")
        elif pair is not None:
            if pair.vector:
                lines.extend(
                    _union_vector_cache_load_lines(
                        pair,
                        target=local,
                        indent="        ",
                    )
                )
            else:
                lines.extend(
                    _union_cache_load_lines(
                        pair,
                        target=local,
                        indent="        ",
                    )
                )
        elif field.id in nested_targets:
            lines.append(f"        {local} = self.{property_name}_view()")
        elif field.type.base_type in _SCALARS:
            if unpacker is not None:
                continue
            lines.extend(
                _scalar_load_lines(
                    context,
                    field,
                    struct=item.is_struct,
                    target=local,
                    indent="        ",
                    use_table_locals=use_table_locals,
                )
            )
        else:
            lines.extend(
                _complex_cache_load_lines(
                    context,
                    field,
                    target=local,
                    indent="        ",
                )
            )
    lines.append(f"        return {name}(")
    for field in model_fields:
        property_name = _identifier(field.name)
        pair = union_pairs_by_value_id.get(field.id)
        dynamic_pair = dynamic_pairs_by_value_id.get(field.id)
        if dynamic_pair is not None:
            expression = f"_{property_name}.to_model()"
            if not field.required:
                expression = (
                    f"None if _{property_name} is None else {expression}"
                )
        elif pair is not None:
            if pair.vector:
                expression = (
                    f"[item.to_model() for item in _{property_name}]"
                )
            else:
                expression = f"_{property_name}.to_model()"
            if not field.required:
                expression = (
                    f"None if _{property_name} is None else {expression}"
                )
        elif field.id in nested_targets:
            expression = f"_{property_name}.to_model()"
            if not field.required:
                expression = (
                    f"None if _{property_name} is None else {expression}"
                )
        elif field.type.base_type in _SCALARS:
            expression = f"_{property_name}"
        elif item.is_struct:
            expression = f"_{property_name}.to_model()"
        else:
            expression = _model_conversion_expression(
                context,
                field,
                f"_{property_name}",
            )
        lines.append(f"            {property_name}={expression},")
    lines.append("        )")
    return lines


def _native_plan_default(
    context: _Context,
    field: FieldDefinition,
) -> bool | int | float | None:
    if field.optional:
        return None
    if field.type.base_type is BaseType.BOOL:
        return bool(field.default_integer)
    if field.type.base_type in (BaseType.FLOAT, BaseType.DOUBLE):
        return field.default_real
    if field.type.base_type in _SCALARS:
        return field.default_integer
    return None


def _native_field_plan(
    context: _Context,
    owner: ObjectDefinition,
    field: FieldDefinition,
    union_pair: _UnionPair | None,
    dynamic_pair: _DynamicPair | None,
) -> dict[str, object]:
    type_ref = field.type
    plan: dict[str, object] = {
        "name": _identifier(field.name),
        "slot": field.id,
        "offset": field.offset,
        "optional": field.optional,
        "required": field.required,
        "default": _native_plan_default(context, field),
    }
    if union_pair is not None:
        plan.update(
            kind="union_vector" if union_pair.vector else "union",
            type_slot=union_pair.type_field.id,
            type_scalar=context.scalar_spec(
                union_pair.enum.underlying_type.base_type
            ).runtime_name,
            arms=[
                {"tag": arm.tag, "target": arm.object.name}
                for arm in union_pair.arms
            ],
        )
        return plan
    if dynamic_pair is not None:
        plan.update(
            kind="dynamic",
            type_slot=dynamic_pair.type_field.id,
            allowed_prefix=dynamic_pair.allowed_prefix,
        )
        return plan
    nested = context.nested_target(owner, field)
    if nested is not None:
        plan.update(kind="nested", target=nested.name)
        return plan
    if type_ref.base_type in _SCALARS:
        plan.update(
            kind="scalar",
            scalar=context.scalar_spec(type_ref.base_type).runtime_name,
        )
    elif type_ref.base_type is BaseType.STRING:
        plan["kind"] = "string"
    elif type_ref.base_type is BaseType.OBJECT:
        target = context.object_for(type_ref)
        plan.update(
            kind="struct" if target.is_struct else "table",
            target=target.name,
        )
    elif type_ref.base_type is BaseType.VECTOR:
        if _is_byte_vector(type_ref):
            plan["kind"] = "vector_byte"
        elif type_ref.element in _SCALARS:
            plan.update(
                kind="vector_scalar",
                scalar=context.scalar_spec(type_ref.element).runtime_name,
            )
        elif type_ref.element is BaseType.STRING:
            plan["kind"] = "vector_string"
        elif type_ref.element is BaseType.OBJECT:
            target = context.object_for(type_ref)
            plan.update(
                kind="vector_struct" if target.is_struct else "vector_table",
                target=target.name,
            )
        else:  # pragma: no cover - rejected by earlier generation checks
            raise GenerationError(
                f"unsupported native vector element {type_ref.element.name}"
            )
    else:  # pragma: no cover - rejected by earlier generation checks
        raise GenerationError(f"unsupported native field type {type_ref.base_type.name}")
    return plan


def _native_module_plan_bytes(context: _Context) -> bytes:
    objects: list[dict[str, object]] = []
    for item in context.schema.objects:
        union_pairs = context.union_pairs(item)
        dynamic_pairs = context.dynamic_pairs(item)
        union_by_value = {pair.value_field.id: pair for pair in union_pairs}
        dynamic_by_value = {pair.value_field.id: pair for pair in dynamic_pairs}
        hidden_type_field_ids = _hidden_type_field_ids(
            union_pairs,
            dynamic_pairs,
        )
        fields = [
            _native_field_plan(
                context,
                item,
                field,
                union_by_value.get(field.id),
                dynamic_by_value.get(field.id),
            )
            for field in _field_order(item)
            if field.id not in hidden_type_field_ids
        ]
        objects.append(
            {
                "name": item.name,
                "is_struct": item.is_struct,
                "byte_size": item.byte_size,
                "min_alignment": item.min_alignment,
                "fields": fields,
            }
        )
    return msgspec.msgpack.encode({"version": 1, "objects": objects})


def _render_root_builder(context: _Context, root: ObjectDefinition) -> list[str]:
    name = _short_name(root.name)
    function_name = f"build_{_snake_case(name)}"
    identifier = (
        repr(context.schema.file_identifier)
        if context.schema.file_identifier is not None
        else "None"
    )
    return [
        f"def {function_name}(",
        f"    value: {name},",
        "    *,",
        "    size_prefixed: bool = False,",
        "    initial_size: int = 0,",
        ") -> memoryview:",
        "    return _FB_NATIVE_MODULE.pack(",
        f"        {root.name!r},",
        "        value,",
        f"        identifier={identifier},",
        "        size_prefixed=size_prefixed,",
        "        initial_size=initial_size,",
        "    )",
    ]


def render_module(
    schema: Schema,
    declaration_file: str,
    *,
    package_prefix: Iterable[str] = (),
) -> str:
    """Render one deterministic Python module for one declaring ``.fbs`` file."""

    prefix = tuple(_snake_case(part) for part in package_prefix)
    context = _Context(schema, declaration_file, prefix)
    local_objects = [
        item for item in schema.objects if item.declaration_file == declaration_file
    ]
    local_enums = [
        item for item in schema.enums if item.declaration_file == declaration_file
    ]
    if not local_objects and not local_enums:
        raise GenerationError(f"no definitions declared in {declaration_file!r}")
    dynamic_field_pairs = [
        (item, pair)
        for item in local_objects
        for pair in context.dynamic_pairs(item)
    ]
    dynamic_value_field_ids = {
        (item.name, pair.value_field.id)
        for item, pair in dynamic_field_pairs
    }
    has_dynamic = bool(dynamic_field_pairs)
    has_byte_vector_helpers = any(
        _is_byte_vector(field.type)
        and context.nested_target(item, field) is None
        and (item.name, field.id) not in dynamic_value_field_ids
        for item in local_objects
        for field in item.fields
    )
    has_unions = any(item.is_union for item in local_enums) or any(
        context.union_pairs(item) for item in local_objects
    )
    typing_imports: list[str] = []
    if has_byte_vector_helpers:
        typing_imports.extend(("Any", "TypeVar"))
    if has_unions:
        typing_imports.append("cast")

    namespaces = {
        _namespace(item.name) for item in [*local_objects, *local_enums]
    }
    if len(namespaces) > 1:
        raise GenerationError(
            "one .fbs file declaring multiple namespaces is not supported yet"
        )

    root = None
    if schema.root_table is not None:
        candidate = schema.object(schema.root_table)
        if candidate.declaration_file == declaration_file:
            root = candidate
    dynamic_extension = False
    for item in local_objects:
        if not _has_marker_attribute(item, "dynamic_extension"):
            continue
        if item.is_struct or item is not root:
            raise GenerationError(
                f"dynamic extension {item.name} must be this file's root table"
            )
        dynamic_extension = True

    object_imports, enum_imports = context.referenced_definitions(
        local_objects,
        local_enums,
    )
    imported_origins: dict[str, set[str]] = defaultdict(set)
    for module in set(object_imports) | set(enum_imports):
        for imported_name in (
            object_imports.get(module, set()) | enum_imports.get(module, set())
        ):
            imported_origins[imported_name].add(module)
    local_symbols = {
        symbol
        for item in local_objects
        for name in (_short_name(item.name),)
        for symbol in (
            name,
            f"{name}View",
        )
    }
    for item in local_enums:
        enum_name = _short_name(item.name)
        local_symbols.add(enum_name)
        if item.is_union:
            local_symbols.add(f"_FB_UNION_{enum_name}")
    local_symbols.update(
        _dynamic_value_type_name(item, pair)
        for item, pair in dynamic_field_pairs
    )
    for imported_name, modules in sorted(
        imported_origins.items(),
        key=lambda item: (item[0].startswith("_"), item[0]),
    ):
        if len(modules) > 1 or imported_name in local_symbols:
            origins = ", ".join(sorted(modules))
            raise GenerationError(
                f"generated symbol collision for {imported_name!r} from {origins}"
            )
    scalar_readers = {
        _SCALAR_READERS[field.type.base_type]
        for item in local_objects
        for field in item.fields
        if field.type.base_type in _SCALARS
    }
    for item in local_objects:
        for pair in context.union_pairs(item):
            if pair.vector:
                scalar_readers.add(
                    _SCALAR_READERS[pair.enum.underlying_type.base_type]
                )
    if any(
        not item.is_struct
        and any(field.type.base_type in _SCALARS for field in item.fields)
        for item in local_objects
    ):
        scalar_readers.add(("_UINT16", "<H"))
    struct_unpackers = [
        unpacker
        for item in local_objects
        if (unpacker := _struct_unpacker(context, item)) is not None
    ]
    lines = [
        _GENERATED_HEADER,
        f"# Source: {declaration_file}",
        "from __future__ import annotations",
        "",
        "import struct",
        *(
            [f"from typing import {', '.join(typing_imports)}"]
            if typing_imports
            else []
        ),
        "",
        "import msgspec",
        "import numpy as np",
        "import numpy.typing as npt",
        "",
        "from msgspec_flatbuffers import (",
        "    InvalidBufferError,",
        "    OpenIntEnum,",
        "    StringVector,",
        "    StructVector,",
        "    StructView,",
        "    TableVector,",
        "    TableView,",
        *(
            ["    DynamicValue,", "    DynamicView,"]
            if has_dynamic
            else []
        ),
        *(["    register_dynamic_type,"] if dynamic_extension else []),
        *(["    UnionDispatch,", "    UnionVector,"] if has_unions else []),
        ")",
        "from msgspec_flatbuffers._native import NativePlan as _NativePlan",
    ]
    for module in sorted(set(object_imports) | set(enum_imports)):
        names = sorted(object_imports.get(module, set()) | enum_imports.get(module, set()))
        lines.append(f"from {module} import {', '.join(names)}")

    if has_byte_vector_helpers:
        lines.extend(("", '_NestedViewT = TypeVar("_NestedViewT", bound=TableView)'))
    if scalar_readers or struct_unpackers:
        lines.append("")
    for reader, fmt in sorted(scalar_readers):
        lines.append(f"{reader} = struct.Struct({fmt!r})")
    for unpacker, fmt in struct_unpackers:
        lines.append(f"{unpacker} = struct.Struct({fmt!r})")
    lines.extend(
        ("", f"_FB_NATIVE_MODULE = _NativePlan({_native_module_plan_bytes(context)!r})")
    )

    for item in local_enums:
        lines.extend(("", "", *_render_enum(context, item)))
    for item, pair in dynamic_field_pairs:
        lines.extend(("", "", *_render_dynamic_value_type(item, pair)))
    for item in local_objects:
        lines.extend(("", "", *_render_model(context, item, item is root)))
    bound_objects = {
        item.name: item
        for item in context.schema.objects
        if item.declaration_file == declaration_file
        or (
            (module := _definition_module(
                item.name,
                item.declaration_file,
                context.package_prefix,
            ))
            in object_imports
            and _short_name(item.name) in object_imports[module]
        )
    }
    if bound_objects:
        lines.extend(("", "", "_FB_NATIVE_MODULE.bind_types({"))
        lines.extend(
            f"    {name!r}: {_short_name(item.name)},"
            for name, item in sorted(bound_objects.items())
        )
        lines.append("})")
    for item in local_objects:
        lines.extend(("", "", *_render_view(context, item, item is root)))
    for item in local_enums:
        if item.is_union:
            lines.extend(("", "", *_render_union_dispatch(context, item)))
    if root is not None:
        lines.extend(("", "", *_render_root_builder(context, root)))
    if dynamic_extension and root is not None:
        root_name = _short_name(root.name)
        lines.extend(
            (
                "",
                "",
                f"register_dynamic_type({root_name}, {root_name}View)",
            )
        )

    exported = [
        *(_short_name(item.name) for item in local_enums),
        *(
            name
            for item in local_objects
            for name in (_short_name(item.name), f"{_short_name(item.name)}View")
        ),
    ]
    if root is not None:
        exported.append(f"build_{_snake_case(_short_name(root.name))}")
    lines.extend(("", "", f"__all__ = {exported!r}", ""))
    return "\n".join(lines)


def _source_declaration(source: Path, project_root: Path) -> str:
    try:
        relative = source.relative_to(project_root)
    except ValueError as error:
        raise GenerationError(
            f"schema {source} is outside project root {project_root}"
        ) from error
    return f"//{relative.as_posix()}"


def generate(
    schema_path: StrPath,
    output_dir: StrPath,
    *,
    include_dirs: Iterable[StrPath] = (),
    flatc: StrPath = "flatc",
    project_root: StrPath | None = None,
    package: str | None = None,
) -> Path:
    """Generate one Python module for one FlatBuffers IDL file."""

    source = Path(schema_path).resolve()
    root = source.parent if project_root is None else Path(project_root).resolve()
    schema = compile_schema(
        source,
        include_dirs=include_dirs,
        flatc=flatc,
        project_root=root,
    )
    declaration_file = _source_declaration(source, root)
    definitions = [
        item
        for item in [*schema.objects, *schema.enums]
        if item.declaration_file == declaration_file
    ]
    if not definitions:
        raise GenerationError(
            f"compiled schema does not contain declarations for {declaration_file}"
        )

    namespaces = {_namespace(item.name) for item in definitions}
    if len(namespaces) != 1:
        raise GenerationError(
            "one .fbs file declaring multiple namespaces is not supported yet"
        )
    namespace = next(iter(namespaces))
    prefix = tuple(part for part in (package or "").split(".") if part)
    package_parts = (*(_snake_case(part) for part in prefix), *(_snake_case(part) for part in namespace))
    target_dir = Path(output_dir).resolve().joinpath(*package_parts)
    target_dir.mkdir(parents=True, exist_ok=True)

    current = Path(output_dir).resolve()
    for part in package_parts:
        current /= part
        init = current / "__init__.py"
        if not init.exists():
            init.write_text("", encoding="utf-8")

    target = target_dir / f"{_snake_case(source.stem)}.py"
    if target.exists():
        expected_header = [_GENERATED_HEADER, f"# Source: {declaration_file}"]
        actual_header = target.read_text(encoding="utf-8").splitlines()[:2]
        if actual_header != expected_header:
            raise GenerationError(f"refusing to overwrite non-generated file: {target}")

    target.write_text(
        render_module(schema, declaration_file, package_prefix=prefix),
        encoding="utf-8",
    )
    return target


__all__ = ["GenerationError", "generate", "render_module"]
