"""Generate msgspec models and lazy FlatBuffers views from reflected schemas.

Example:
    Generate Python modules from one IDL file:

    >>> generate("schemas/monster.fbs", "generated")
    PosixPath('generated/example/monster.py')
"""

from __future__ import annotations

import keyword
import re
from collections import defaultdict
from collections.abc import Iterable, Sequence
from functools import lru_cache
from math import isnan
from pathlib import Path
from typing import NamedTuple

import msgspec

from ._dynamic import (
    _MSGSPEC_TAG_FIELD,
    _OPAQUE_DATA_FIELD,
    dynamic_allow_prefix,
)
from ._version import __version__ as _GENERATOR_VERSION
from .compiler import StrPath, compile_schema
from .schema import (
    BaseType,
    EnumDefinition,
    FieldDefinition,
    ObjectDefinition,
    Schema,
    TypeReference,
)

_GENERATED_HEADER = "# Generated by msgspec-serde. DO NOT EDIT."


class GenerationError(ValueError):
    """Report that a schema cannot be represented by the generator.

    Example:
        Catch generation errors separately from compiler errors:

        >>> try:
        ...     generate("unsupported.fbs", "generated")
        ... except GenerationError as error:
        ...     print(error)
    """


class _ScalarSpec(NamedTuple):
    python_type: str
    runtime_name: str
    numpy_type: str
    size: int


class _UnionArm(NamedTuple):
    tag: int
    object: ObjectDefinition


class _UnionPair(NamedTuple):
    value_field: FieldDefinition
    type_field: FieldDefinition
    enum: EnumDefinition
    arms: tuple[_UnionArm, ...]
    vector: bool


class _DynamicPair(NamedTuple):
    value_field: FieldDefinition
    type_field: FieldDefinition
    allowed_prefix: str


def _hidden_type_field_ids(
    union_pairs: Sequence[_UnionPair],
    dynamic_pairs: Sequence[_DynamicPair],
) -> set[int]:
    return {pair.type_field.id for pair in union_pairs} | {
        pair.type_field.id for pair in dynamic_pairs
    }


_SCALARS: dict[BaseType, _ScalarSpec] = {
    BaseType.UTYPE: _ScalarSpec("int", "uint8", "np.uint8", 1),
    BaseType.BOOL: _ScalarSpec("bool", "bool", "np.bool_", 1),
    BaseType.BYTE: _ScalarSpec("int", "int8", "np.int8", 1),
    BaseType.UBYTE: _ScalarSpec("int", "uint8", "np.uint8", 1),
    BaseType.SHORT: _ScalarSpec("int", "int16", "np.int16", 2),
    BaseType.USHORT: _ScalarSpec("int", "uint16", "np.uint16", 2),
    BaseType.INT: _ScalarSpec("int", "int32", "np.int32", 4),
    BaseType.UINT: _ScalarSpec("int", "uint32", "np.uint32", 4),
    BaseType.LONG: _ScalarSpec("int", "int64", "np.int64", 8),
    BaseType.ULONG: _ScalarSpec("int", "uint64", "np.uint64", 8),
    BaseType.FLOAT: _ScalarSpec("float", "float32", "np.float32", 4),
    BaseType.DOUBLE: _ScalarSpec("float", "float64", "np.float64", 8),
}

_NUMPY_DTYPES: dict[BaseType, str] = {
    BaseType.UTYPE: "<u1",
    BaseType.BOOL: "?",
    BaseType.BYTE: "<i1",
    BaseType.UBYTE: "<u1",
    BaseType.SHORT: "<i2",
    BaseType.USHORT: "<u2",
    BaseType.INT: "<i4",
    BaseType.UINT: "<u4",
    BaseType.LONG: "<i8",
    BaseType.ULONG: "<u8",
    BaseType.FLOAT: "<f4",
    BaseType.DOUBLE: "<f8",
}

_SCALAR_READERS: dict[BaseType, tuple[str, str]] = {
    BaseType.UTYPE: ("_UINT8", "<B"),
    BaseType.BOOL: ("_BOOL", "<?"),
    BaseType.BYTE: ("_INT8", "<b"),
    BaseType.UBYTE: ("_UINT8", "<B"),
    BaseType.SHORT: ("_INT16", "<h"),
    BaseType.USHORT: ("_UINT16", "<H"),
    BaseType.INT: ("_INT32", "<i"),
    BaseType.UINT: ("_UINT32", "<I"),
    BaseType.LONG: ("_INT64", "<q"),
    BaseType.ULONG: ("_UINT64", "<Q"),
    BaseType.FLOAT: ("_FLOAT32", "<f"),
    BaseType.DOUBLE: ("_FLOAT64", "<d"),
}


def _is_byte_vector(type_ref: TypeReference) -> bool:
    return (
        type_ref.base_type is BaseType.VECTOR
        and type_ref.element is BaseType.UBYTE
        and type_ref.index < 0
    )


@lru_cache(maxsize=4096)
def _snake_case(value: str) -> str:
    value = re.sub(r"(?<=[a-z0-9])(?=[A-Z])", "_", value)
    value = re.sub(r"[^0-9A-Za-z_]", "_", value).lower()
    if value and value[0].isdigit():
        value = f"_{value}"
    return value or "generated"


@lru_cache(maxsize=4096)
def _pascal_case(value: str) -> str:
    return "".join(part.capitalize() for part in _snake_case(value).split("_") if part)


@lru_cache(maxsize=4096)
def _identifier(value: str) -> str:
    value = re.sub(r"\W", "_", value)
    if value and value[0].isdigit():
        value = f"_{value}"
    if keyword.iskeyword(value):
        value = f"{value}_"
    return value


@lru_cache(maxsize=4096)
def _short_name(qualified_name: str) -> str:
    return _identifier(qualified_name.rsplit(".", 1)[-1])


@lru_cache(maxsize=4096)
def _namespace(qualified_name: str) -> tuple[str, ...]:
    parts = qualified_name.split(".")
    return tuple(parts[:-1])


def _declaration_path(declaration_file: str | None) -> str:
    if declaration_file is None:
        raise GenerationError("flatc did not record a declaration file")
    return declaration_file.removeprefix("//")


def _definition_module(
    qualified_name: str,
    declaration_file: str | None,
    package_prefix: tuple[str, ...],
    *,
    gen_onefile: bool = False,
) -> str:
    if gen_onefile:
        namespace = ()
        module_name = Path(_declaration_path(declaration_file)).stem
    else:
        namespace = tuple(_snake_case(part) for part in _namespace(qualified_name))
        module_name = _short_name(qualified_name)
    module = _snake_case(module_name)
    return ".".join((*package_prefix, *namespace, module))


@lru_cache(maxsize=1024)
def _field_order(item: ObjectDefinition) -> tuple[FieldDefinition, ...]:
    fields = [field for field in item.fields if not field.deprecated]
    key = (lambda field: field.offset) if item.is_struct else (lambda field: field.id)
    return tuple(sorted(fields, key=key))


def _find_identifier_collision(
    names: Iterable[str],
) -> tuple[str, str, str] | None:
    generated: dict[str, str] = {}
    for name in names:
        identifier = _identifier(name)
        previous = generated.get(identifier)
        if previous is not None:
            return previous, name, identifier
        generated[identifier] = name
    return None


def _validate_member_names(
    objects: Sequence[ObjectDefinition],
    enums: Sequence[EnumDefinition],
) -> None:
    for item in objects:
        collision = _find_identifier_collision(
            field.name for field in item.fields if not field.deprecated
        )
        if collision is not None:
            previous, name, identifier = collision
            kind = "struct" if item.is_struct else "table"
            raise GenerationError(
                f"{kind} {item.name} fields {previous!r} and {name!r} "
                f"both generate Python name {identifier!r}"
            )

    for item in enums:
        collision = _find_identifier_collision(value.name for value in item.values)
        if collision is not None:
            previous, name, identifier = collision
            raise GenerationError(
                f"enum {item.name} values {previous!r} and {name!r} "
                f"both generate Python name {identifier!r}"
            )


def _local_symbols(
    objects: Sequence[ObjectDefinition],
    enums: Sequence[EnumDefinition],
) -> set[str]:
    generated: dict[str, str] = {}
    candidates = [
        (symbol, item.name)
        for item in objects
        for symbol in (_short_name(item.name), f"{_short_name(item.name)}View")
    ]
    candidates.extend((_short_name(item.name), item.name) for item in enums)
    for symbol, source in candidates:
        previous = generated.get(symbol)
        if previous is not None:
            raise GenerationError(
                f"definitions {previous!r} and {source!r} both generate "
                f"Python symbol {symbol!r}"
            )
        generated[symbol] = source
    return set(generated).union(
        f"_FB_UNION_{_short_name(item.name)}" for item in enums if item.is_union
    )


class _Context:
    def __init__(
        self,
        schema: Schema,
        package_prefix: tuple[str, ...],
        local_names: frozenset[str],
        gen_onefile: bool,
    ) -> None:
        self.schema = schema
        self.package_prefix = package_prefix
        self.local_names = local_names
        self.gen_onefile = gen_onefile
        self._nested_targets: dict[tuple[str, int], ObjectDefinition | None] = {}
        self._union_arms: dict[str, tuple[_UnionArm, ...]] = {}
        self._union_arm_names: frozenset[str] | None = None
        self._union_pairs: dict[str, tuple[_UnionPair, ...]] = {}
        self._dynamic_pairs: dict[str, tuple[_DynamicPair, ...]] = {}
        self._key_fields: dict[str, FieldDefinition | None] = {}
        self.reachable_object_names = local_names & {
            item.name for item in schema.objects
        }
        self.reachable_enum_names = local_names & {item.name for item in schema.enums}

    def module_alias(self, module: str) -> str:
        encoded = "_".join(
            f"{len(component)}_{component}" for component in module.split(".")
        )
        return f"_fb_import_{encoded}"

    def definition_module(
        self,
        qualified_name: str,
        declaration_file: str | None,
    ) -> str:
        return _definition_module(
            qualified_name,
            declaration_file,
            self.package_prefix,
            gen_onefile=self.gen_onefile,
        )

    def _symbol_name(
        self,
        qualified_name: str,
        declaration_file: str | None,
        symbol: str,
    ) -> str:
        if qualified_name in self.local_names:
            return symbol
        module = self.definition_module(qualified_name, declaration_file)
        return f"{self.module_alias(module)}.{symbol}"

    def model_name(self, item: ObjectDefinition) -> str:
        return self._symbol_name(
            item.name,
            item.declaration_file,
            _short_name(item.name),
        )

    def view_name(self, item: ObjectDefinition) -> str:
        return f"{self.model_name(item)}View"

    def enum_name(self, item: EnumDefinition) -> str:
        return self._symbol_name(
            item.name,
            item.declaration_file,
            _short_name(item.name),
        )

    def union_dispatch_name(self, item: EnumDefinition) -> str:
        return self._symbol_name(
            item.name,
            item.declaration_file,
            f"_FB_UNION_{_short_name(item.name)}",
        )

    def object_for(self, type_ref: TypeReference) -> ObjectDefinition:
        if type_ref.index < 0 or type_ref.index >= len(self.schema.objects):
            raise GenerationError(f"invalid object type index {type_ref.index}")
        return self.schema.objects[type_ref.index]

    def enum_for(self, type_ref: TypeReference) -> EnumDefinition | None:
        if type_ref.index < 0:
            return None
        if type_ref.index >= len(self.schema.enums):
            raise GenerationError(f"invalid enum type index {type_ref.index}")
        return self.schema.enums[type_ref.index]

    def nested_target(
        self,
        owner: ObjectDefinition,
        field: FieldDefinition,
    ) -> ObjectDefinition | None:
        cache_key = (owner.name, field.id)
        if cache_key in self._nested_targets:
            return self._nested_targets[cache_key]
        target_name = field.nested_flatbuffer
        if target_name is None:
            self._nested_targets[cache_key] = None
            return None
        if not _is_byte_vector(field.type):
            raise GenerationError(
                f"nested_flatbuffer field {owner.name}.{field.name} "
                "must be a [ubyte] vector"
            )
        if "." in target_name:
            candidates = (target_name,)
        else:
            namespace = ".".join(_namespace(owner.name))
            candidates = (f"{namespace}.{target_name}" if namespace else target_name,)
        matches = [item for item in self.schema.objects if item.name in candidates]
        if len(matches) != 1:
            raise GenerationError(
                f"nested_flatbuffer target {target_name!r} for "
                f"{owner.name}.{field.name} was not found"
            )
        target = matches[0]
        if target.is_struct:
            raise GenerationError(
                f"nested_flatbuffer target {target.name} must be a table"
            )
        self._nested_targets[cache_key] = target
        return target

    def union_enum(self, type_ref: TypeReference) -> EnumDefinition:
        enum = self.enum_for(type_ref)
        if enum is None or not enum.is_union:
            raise GenerationError("union field does not reference a union enum")
        return enum

    def union_arms(self, enum: EnumDefinition) -> tuple[_UnionArm, ...]:
        cached = self._union_arms.get(enum.name)
        if cached is not None:
            return cached
        if enum.underlying_type.base_type is not BaseType.UTYPE:
            raise GenerationError(f"union {enum.name} must use the UTYPE discriminator")
        none_values = [
            value
            for value in enum.values
            if value.union_type is not None
            and value.union_type.base_type is BaseType.NONE
        ]
        if len(none_values) != 1:
            raise GenerationError(
                f"union {enum.name} must define exactly one NONE alternative"
            )
        if none_values[0].value != 0:
            raise GenerationError(f"union {enum.name} NONE alternative must have tag 0")
        seen_objects: set[int] = set()
        seen_tags = {0}
        arms: list[_UnionArm] = []
        for value in enum.values:
            union_type = value.union_type
            if union_type is None:
                raise GenerationError(
                    f"union alternative {enum.name}.{value.name} has no type"
                )
            if union_type.base_type is BaseType.NONE:
                continue
            if value.value < 1 or value.value > 255:
                raise GenerationError(
                    f"union alternative {enum.name}.{value.name} tag "
                    f"{value.value} is outside uint8 range"
                )
            if value.value in seen_tags:
                raise GenerationError(
                    f"union {enum.name} has duplicate discriminator tag {value.value}"
                )
            seen_tags.add(value.value)
            if union_type.base_type is not BaseType.OBJECT:
                raise GenerationError(
                    f"unsupported union alternative {enum.name}.{value.name}: "
                    f"{union_type.base_type.name.lower()}"
                )
            target = self.object_for(union_type)
            if target.is_struct:
                raise GenerationError(
                    f"unsupported union struct alternative {enum.name}.{value.name}"
                )
            if union_type.index in seen_objects:
                raise GenerationError(f"union aliases are not supported: {enum.name}")
            seen_objects.add(union_type.index)
            arms.append(_UnionArm(value.value, target))
        if not arms:
            raise GenerationError(f"union {enum.name} has no table alternatives")
        result = tuple(arms)
        self._union_arms[enum.name] = result
        return result

    def union_pairs(self, item: ObjectDefinition) -> tuple[_UnionPair, ...]:
        cached = self._union_pairs.get(item.name)
        if cached is not None:
            return cached
        if item.is_struct and any(
            field.type.base_type is BaseType.UNION
            or (
                field.type.base_type is BaseType.VECTOR
                and field.type.element is BaseType.UNION
            )
            for field in item.fields
        ):
            raise GenerationError(
                f"FlatBuffers struct {item.name} cannot contain unions"
            )
        fields = _field_order(item)
        by_id = {field.id: field for field in fields}
        if len(by_id) != len(fields):
            raise GenerationError(f"object {item.name} has duplicate field ids")
        pairs: list[_UnionPair] = []
        paired_type_field_ids: set[int] = set()
        for value_field in fields:
            type_ref = value_field.type
            scalar_union = type_ref.base_type is BaseType.UNION
            vector_union = (
                type_ref.base_type is BaseType.VECTOR
                and type_ref.element is BaseType.UNION
            )
            if not scalar_union and not vector_union:
                continue
            enum = self.union_enum(type_ref)
            type_field = by_id.get(value_field.id - 1)
            expected_name = f"{value_field.name}_type"
            if type_field is None or type_field.name != expected_name:
                raise GenerationError(
                    f"union field {item.name}.{value_field.name} has no matching "
                    f"{expected_name!r} discriminator"
                )
            type_type = type_field.type
            if scalar_union:
                valid_type = type_type.base_type is BaseType.UTYPE
            else:
                valid_type = (
                    type_type.base_type is BaseType.VECTOR
                    and type_type.element is BaseType.UTYPE
                )
            if not valid_type or type_type.index != type_ref.index:
                raise GenerationError(
                    f"union field {item.name}.{value_field.name} has a malformed "
                    "discriminator pair"
                )
            paired_type_field_ids.add(type_field.id)
            pairs.append(
                _UnionPair(
                    value_field,
                    type_field,
                    enum,
                    self.union_arms(enum),
                    vector_union,
                )
            )
        for field in fields:
            can_be_discriminator = field.type.base_type is BaseType.UTYPE or (
                field.type.base_type is BaseType.VECTOR
                and field.type.element is BaseType.UTYPE
            )
            if not can_be_discriminator:
                continue
            enum = self.enum_for(field.type)
            is_union_type = enum is not None and enum.is_union
            if is_union_type and field.id not in paired_type_field_ids:
                raise GenerationError(
                    f"orphan union discriminator {item.name}.{field.name}"
                )
        result = tuple(pairs)
        self._union_pairs[item.name] = result
        return result

    def is_union_arm(self, item: ObjectDefinition) -> bool:
        names = self._union_arm_names
        if names is None:
            names = frozenset(
                arm.object.name
                for enum in self.schema.enums
                if enum.is_union
                for arm in self.union_arms(enum)
            )
            self._union_arm_names = names
        return item.name in names

    def dynamic_pairs(self, item: ObjectDefinition) -> tuple[_DynamicPair, ...]:
        cached = self._dynamic_pairs.get(item.name)
        if cached is not None:
            return cached
        fields = _field_order(item)
        by_name = {field.name: field for field in fields}
        pairs: list[_DynamicPair] = []
        paired_type_field_ids: set[int] = set()
        for value_field in fields:
            type_field_name = value_field.dynamic_flatbuffer
            if type_field_name is None:
                continue
            payload_name = f"{item.name}.{value_field.name}"
            if item.is_struct:
                raise GenerationError(
                    f"FlatBuffers struct {item.name} cannot contain dynamic fields"
                )
            if not _is_byte_vector(value_field.type):
                raise GenerationError(
                    f"dynamic_flatbuffer field {payload_name} must be a [ubyte] vector"
                )
            if value_field.nested_flatbuffer is not None:
                raise GenerationError(
                    f"field {payload_name} cannot use both "
                    "dynamic_flatbuffer and nested_flatbuffer"
                )
            allow_pattern = value_field.dynamic_allow
            if allow_pattern is None:
                raise GenerationError(
                    f"dynamic_flatbuffer field {payload_name} requires dynamic_allow"
                )
            try:
                allowed_prefix = dynamic_allow_prefix(allow_pattern)
            except ValueError as error:
                raise GenerationError(
                    f"invalid dynamic_allow on {payload_name}: {error}"
                ) from error
            type_field = by_name.get(type_field_name)
            if type_field is None:
                raise GenerationError(
                    f"dynamic_flatbuffer field {payload_name} "
                    f"references missing type field {type_field_name!r}"
                )
            qualified_type_field_name = f"{item.name}.{type_field.name}"
            if (
                type_field.id == value_field.id
                or type_field.id in paired_type_field_ids
            ):
                raise GenerationError(
                    f"dynamic FlatBuffer type field {qualified_type_field_name} "
                    "must belong to exactly one payload"
                )
            if (
                type_field.type.base_type is not BaseType.STRING
                or type_field.required != value_field.required
            ):
                raise GenerationError(
                    f"dynamic FlatBuffer type field {qualified_type_field_name} "
                    "must be a string with matching requiredness"
                )
            paired_type_field_ids.add(type_field.id)
            pairs.append(_DynamicPair(value_field, type_field, allowed_prefix))
        for field in fields:
            if field.dynamic_allow is not None and field.dynamic_flatbuffer is None:
                raise GenerationError(
                    f"field {item.name}.{field.name} uses dynamic_allow without "
                    "dynamic_flatbuffer"
                )
        result = tuple(pairs)
        self._dynamic_pairs[item.name] = result
        return result

    def scalar_spec(self, base_type: BaseType) -> _ScalarSpec:
        try:
            return _SCALARS[base_type]
        except KeyError as error:
            raise GenerationError(
                f"unsupported scalar type {base_type.name}"
            ) from error

    def scalar_python_type(self, type_ref: TypeReference) -> str:
        enum = self.enum_for(type_ref)
        if enum is not None:
            return self.enum_name(enum)
        return self.scalar_spec(type_ref.base_type).python_type

    def key_field(self, item: ObjectDefinition) -> FieldDefinition | None:
        try:
            return self._key_fields[item.name]
        except KeyError:
            pass
        keys = [field for field in _field_order(item) if field.key]
        if len(keys) > 1:
            raise GenerationError(f"table {item.name} has multiple key fields")
        key = keys[0] if keys else None
        if key is not None and (
            item.is_struct
            or (
                key.type.base_type not in _SCALARS
                and key.type.base_type is not BaseType.STRING
            )
        ):
            raise GenerationError(
                f"key field {item.name}.{key.name} must be a table scalar or string"
            )
        self._key_fields[item.name] = key
        return key

    def table_key_field(self, item: ObjectDefinition) -> FieldDefinition | None:
        return None if item.is_struct else self.key_field(item)

    def key_python_type(self, field: FieldDefinition) -> str:
        if field.type.base_type is BaseType.STRING:
            return "str"
        return self.scalar_python_type(field.type)

    def model_type(self, type_ref: TypeReference) -> str:
        if type_ref.base_type in _SCALARS:
            return self.scalar_python_type(type_ref)
        if type_ref.base_type is BaseType.STRING:
            return "str"
        if type_ref.base_type is BaseType.OBJECT:
            return self.model_name(self.object_for(type_ref))
        if type_ref.base_type is BaseType.VECTOR:
            return self.vector_model_type(type_ref)
        if type_ref.base_type is BaseType.ARRAY:
            return self.array_model_type(type_ref)
        raise GenerationError(f"unsupported model type {type_ref.base_type.name}")

    def vector_model_type(self, type_ref: TypeReference) -> str:
        element = type_ref.element
        if _is_byte_vector(type_ref):
            return "bytes"
        if element in _SCALARS:
            enum = self.enum_for(type_ref)
            if enum is not None:
                return f"list[{self.enum_name(enum)}]"
            return f"npt.NDArray[{self.scalar_spec(element).numpy_type}]"
        if element is BaseType.STRING:
            return "list[str]"
        if element is BaseType.OBJECT:
            item = self.object_for(type_ref)
            key = self.table_key_field(item)
            if key is not None:
                return f"dict[{self.key_python_type(key)}, {self.model_name(item)}]"
            return f"list[{self.model_name(item)}]"
        raise GenerationError(f"unsupported vector element type {element.name}")

    def array_model_type(self, type_ref: TypeReference) -> str:
        element = type_ref.element
        if element in _SCALARS:
            enum = self.enum_for(type_ref)
            if enum is not None:
                return f"list[{self.enum_name(enum)}]"
            return f"npt.NDArray[{self.scalar_spec(element).numpy_type}]"
        if element is BaseType.OBJECT:
            return f"list[{self.model_name(self.object_for(type_ref))}]"
        raise GenerationError(f"unsupported array element type {element.name}")

    def view_type(self, type_ref: TypeReference) -> str:
        if type_ref.base_type in _SCALARS:
            return self.scalar_python_type(type_ref)
        if type_ref.base_type is BaseType.STRING:
            return "str"
        if type_ref.base_type is BaseType.OBJECT:
            return self.view_name(self.object_for(type_ref))
        if type_ref.base_type is BaseType.VECTOR:
            return self.vector_view_type(type_ref)
        if type_ref.base_type is BaseType.ARRAY:
            return self.array_view_type(type_ref)
        raise GenerationError(f"unsupported view type {type_ref.base_type.name}")

    def vector_view_type(self, type_ref: TypeReference) -> str:
        element = type_ref.element
        if _is_byte_vector(type_ref):
            return "memoryview"
        if element in _SCALARS:
            dtype = self.scalar_spec(element).numpy_type
            return f"npt.NDArray[{dtype}]"
        if element is BaseType.STRING:
            return "StringVector"
        if element is BaseType.OBJECT:
            item = self.object_for(type_ref)
            key = self.table_key_field(item)
            if key is not None:
                return f"TableMap[{self.key_python_type(key)}, {self.view_name(item)}]"
            wrapper = "StructVector" if item.is_struct else "TableVector"
            return f"{wrapper}[{self.view_name(item)}]"
        raise GenerationError(f"unsupported vector element type {element.name}")

    def array_view_type(self, type_ref: TypeReference) -> str:
        element = type_ref.element
        if element in _SCALARS:
            return f"npt.NDArray[{self.scalar_spec(element).numpy_type}]"
        if element is BaseType.OBJECT:
            item = self.object_for(type_ref)
            if not item.is_struct:
                raise GenerationError("FlatBuffers arrays may only contain structs")
            return f"StructVector[{self.view_name(item)}]"
        raise GenerationError(f"unsupported array element type {element.name}")

    def default_expression(self, field: FieldDefinition) -> str:
        if field.optional:
            return "None"
        enum = self.enum_for(field.type)
        if enum is not None:
            return f"{self.enum_name(enum)}({field.default_integer})"
        if field.type.base_type is BaseType.BOOL:
            return repr(bool(field.default_integer))
        if field.type.base_type in (BaseType.FLOAT, BaseType.DOUBLE):
            return _float_literal(field.default_real)
        return repr(field.default_integer)

    def referenced_definitions(
        self,
        local_objects: list[ObjectDefinition],
        local_enums: list[EnumDefinition],
    ) -> tuple[dict[str, set[str]], dict[str, set[str]]]:
        objects: dict[str, set[str]] = defaultdict(set)
        enums: dict[str, set[str]] = defaultdict(set)
        pending_objects = list(local_objects)
        pending_enums = list(local_enums)
        seen_objects: set[str] = set()
        seen_enums: set[str] = set()
        while pending_objects or pending_enums:
            while pending_objects:
                item = pending_objects.pop()
                if item.name in seen_objects:
                    continue
                seen_objects.add(item.name)
                self.dynamic_pairs(item)
                for field in item.fields:
                    target, enum = self._field_dependencies(item, field)
                    if target is not None:
                        self._record_object(objects, target)
                        pending_objects.append(target)
                    if enum is not None:
                        self._record_enum(enums, enum)
                        pending_enums.append(enum)
                for pair in self.union_pairs(item):
                    self._record_enum(enums, pair.enum)
                    pending_enums.append(pair.enum)
                    for arm in pair.arms:
                        self._record_object(objects, arm.object)
                        pending_objects.append(arm.object)
            while pending_enums:
                enum = pending_enums.pop()
                if enum.name in seen_enums:
                    continue
                seen_enums.add(enum.name)
                if enum.is_union:
                    for arm in self.union_arms(enum):
                        self._record_object(objects, arm.object)
                        pending_objects.append(arm.object)
        self.reachable_object_names = frozenset(seen_objects)
        self.reachable_enum_names = frozenset(seen_enums)
        return objects, enums

    def _field_dependencies(
        self,
        owner: ObjectDefinition,
        field: FieldDefinition,
    ) -> tuple[ObjectDefinition | None, EnumDefinition | None]:
        target = self.nested_target(owner, field)
        enum = None
        type_ref = field.type
        if type_ref.base_type is BaseType.OBJECT:
            target = self.object_for(type_ref)
        elif type_ref.base_type in (BaseType.VECTOR, BaseType.ARRAY):
            if type_ref.element is BaseType.OBJECT:
                target = self.object_for(type_ref)
            elif type_ref.element in _SCALARS:
                enum = self.enum_for(type_ref)
        elif type_ref.base_type in _SCALARS:
            enum = self.enum_for(type_ref)
        return target, enum

    def _record_object(
        self,
        imports: dict[str, set[str]],
        item: ObjectDefinition,
    ) -> None:
        if item.name in self.local_names:
            return
        module = self.definition_module(item.name, item.declaration_file)
        name = _short_name(item.name)
        imports[module].update((name, f"{name}View"))

    def _record_enum(
        self,
        imports: dict[str, set[str]],
        item: EnumDefinition,
    ) -> None:
        if item.name in self.local_names:
            return
        module = self.definition_module(item.name, item.declaration_file)
        imports[module].add(_short_name(item.name))
        if item.is_union:
            imports[module].add(f"_FB_UNION_{_short_name(item.name)}")


def _float_literal(value: float) -> str:
    if isnan(value):
        return 'float("nan")'
    if value == float("inf"):
        return 'float("inf")'
    if value == float("-inf"):
        return 'float("-inf")'
    return repr(value)


def _documentation(lines: tuple[str, ...], indent: str = "    ") -> list[str]:
    if not lines:
        return []
    text = "\n".join(lines)
    return [f"{indent}{text!r}"]


def _has_marker_attribute(item: ObjectDefinition, key: str) -> bool:
    matches = [attribute for attribute in item.attributes if attribute.key == key]
    if len(matches) > 1:
        raise GenerationError(f"table {item.name} has duplicate {key!r} attributes")
    if not matches:
        return False
    if matches[0].value not in (None, "0"):
        raise GenerationError(f"table {item.name} attribute {key!r} takes no value")
    return True


def _union_model_type(context: _Context, pair: _UnionPair) -> str:
    return " | ".join(context.model_name(arm.object) for arm in pair.arms)


def _union_view_type(context: _Context, pair: _UnionPair) -> str:
    return " | ".join(context.view_name(arm.object) for arm in pair.arms)


def _dynamic_value_type_name(
    owner: ObjectDefinition,
    pair: _DynamicPair,
) -> str:
    return f"{_short_name(owner.name)}{_pascal_case(pair.value_field.name)}"


def _dynamic_value_type_key(
    owner: ObjectDefinition,
    pair: _DynamicPair,
) -> str:
    return f"@dynamic:{owner.name}.{pair.value_field.name}"


def _render_dynamic_value_type(
    owner: ObjectDefinition,
    pair: _DynamicPair,
) -> list[str]:
    return [
        f"class {_dynamic_value_type_name(owner, pair)}(_FbDynamicValue):",
        "    __slots__ = ()",
        f"    _allowed_prefix = {pair.allowed_prefix!r}",
    ]


def _model_field_line(
    context: _Context,
    owner: ObjectDefinition,
    field: FieldDefinition,
    union_pair: _UnionPair | None,
    dynamic_pair: _DynamicPair | None,
) -> str:
    name = _identifier(field.name)
    nested = context.nested_target(owner, field)
    if dynamic_pair is not None:
        annotation = _dynamic_value_type_name(owner, dynamic_pair)
    elif union_pair is not None:
        union_type = _union_model_type(context, union_pair)
        annotation = f"list[{union_type} | None]" if union_pair.vector else union_type
    elif nested is not None:
        annotation = context.model_name(nested)
    else:
        annotation = context.model_type(field.type)
    if owner.is_struct:
        return f"    {name}: {annotation}"
    if field.type.base_type in _SCALARS:
        if field.optional:
            return f"    {name}: {annotation} | None = None"
        return f"    {name}: {annotation} = {context.default_expression(field)}"
    if field.required:
        return f"    {name}: {annotation}"
    return f"    {name}: {annotation} | None = None"


def _render_enum(context: _Context, item: EnumDefinition) -> list[str]:
    if item.is_union:
        context.union_arms(item)
    name = _short_name(item.name)
    lines = [f"class {name}(_FbOpenIntEnum):"]
    lines.extend(_documentation(item.documentation))
    if not item.values:
        lines.append("    pass")
    else:
        lines.extend(
            f"    {_identifier(value.name)} = {value.value}" for value in item.values
        )
    return lines


def _is_numpy_model_field(context: _Context, field: FieldDefinition) -> bool:
    type_ref = field.type
    return (
        type_ref.base_type in (BaseType.VECTOR, BaseType.ARRAY)
        and type_ref.element in _SCALARS
        and not _is_byte_vector(type_ref)
        and context.enum_for(type_ref) is None
    )


def _model_field_comparison(
    context: _Context,
    field: FieldDefinition,
) -> str:
    name = _identifier(field.name)
    if not _is_numpy_model_field(context, field):
        return f"self.{name} == other.{name}"

    arrays_equal = (
        f"self.{name}.dtype == other.{name}.dtype and "
        f"np.array_equal(self.{name}, other.{name})"
    )
    if field.required:
        return arrays_equal
    return (
        f"(self.{name} is None and other.{name} is None) or "
        f"(self.{name} is not None and other.{name} is not None and "
        f"{arrays_equal})"
    )


def _render_model_equality(
    context: _Context,
    item: ObjectDefinition,
    fields: Sequence[FieldDefinition],
) -> list[str]:
    lines = [
        "    def __eq__(self, other: object) -> bool:",
        "        if type(other) is not type(self):",
        "            return False",
        "        return (",
    ]
    comparisons = [_model_field_comparison(context, field) for field in fields]
    lines.append(f"            ({comparisons[0]})")
    lines.extend(f"            and ({comparison})" for comparison in comparisons[1:])
    lines.extend(
        [
            "        )",
            "",
            "    def __ne__(self, other: object) -> bool:",
            "        return not self == other",
        ]
    )
    return lines


def _render_union_dispatch(context: _Context, item: EnumDefinition) -> list[str]:
    arms = context.union_arms(item)
    none_value = next(
        value
        for value in item.values
        if value.union_type is not None and value.union_type.base_type is BaseType.NONE
    )
    lines = [
        f"_FB_UNION_{_short_name(item.name)} = _FbUnionDispatch(",
        f"    {item.name!r},",
        f"    {none_value.value},",
        "    {",
    ]
    lines.extend(f"        {arm.tag}: {context.view_name(arm.object)}," for arm in arms)
    lines.extend(("    },", ")"))
    return lines


def _render_model(
    context: _Context,
    item: ObjectDefinition,
) -> list[str]:
    name = _short_name(item.name)
    fields = _field_order(item)
    union_pairs = context.union_pairs(item)
    union_pairs_by_value_id = {pair.value_field.id: pair for pair in union_pairs}
    dynamic_pairs = context.dynamic_pairs(item)
    dynamic_pairs_by_value_id = {pair.value_field.id: pair for pair in dynamic_pairs}
    hidden_type_field_ids = _hidden_type_field_ids(union_pairs, dynamic_pairs)
    model_fields = [field for field in fields if field.id not in hidden_type_field_ids]
    has_numeric_vectors = any(
        _is_numpy_model_field(context, field) for field in model_fields
    )
    options = ["kw_only=True"]
    if not item.is_struct:
        field_names = [_identifier(field.name) for field in fields]
        reserved_fields = {
            _MSGSPEC_TAG_FIELD,
            _OPAQUE_DATA_FIELD,
        }
        conflict = next(
            (name for name in field_names if name in reserved_fields),
            None,
        )
        if conflict is not None:
            description = (
                "msgspec tag field"
                if conflict == _MSGSPEC_TAG_FIELD
                else "dynamic payload field"
            )
            raise GenerationError(
                f"table {item.name} uses reserved {description} {conflict!r}"
            )
        if context.is_union_arm(item):
            options.extend(
                (
                    f"tag={item.name!r}",
                    f"tag_field={_MSGSPEC_TAG_FIELD!r}",
                )
            )
    if has_numeric_vectors:
        options.append("eq=False")
    lines = [f"class {name}(msgspec.Struct, {', '.join(options)}):"]
    lines.extend(_documentation(item.documentation))
    if not model_fields:
        lines.append("    pass")
    lines.extend(
        _model_field_line(
            context,
            item,
            field,
            union_pairs_by_value_id.get(field.id),
            dynamic_pairs_by_value_id.get(field.id),
        )
        for field in model_fields
    )
    if has_numeric_vectors:
        lines.append("")
        lines.extend(_render_model_equality(context, item, model_fields))
    return lines


def _scalar_view_property(
    context: _Context,
    field: FieldDefinition,
    struct: bool,
) -> list[str]:
    name = _identifier(field.name)
    annotation = context.scalar_python_type(field.type)
    if field.optional and not struct:
        annotation = f"{annotation} | None"
    body = _scalar_load_lines(
        context,
        field,
        struct=struct,
        target="value",
        indent="        ",
    )
    return [
        "    @property",
        f"    def {name}(self) -> {annotation}:",
        *body,
        "        return value",
    ]


def _scalar_load_lines(
    context: _Context,
    field: FieldDefinition,
    *,
    struct: bool,
    target: str,
    indent: str,
) -> list[str]:
    """Render one checked scalar load without generic runtime dispatch."""

    scalar = context.scalar_spec(field.type.base_type)
    reader, _ = _SCALAR_READERS[field.type.base_type]
    enum = context.enum_for(field.type)
    present = f"{reader}.unpack_from({{buffer}}, {{position}})[0]"
    if enum is not None:
        present = f"{context.enum_name(enum)}({present})"

    if struct:
        return [
            f"{indent}{target} = "
            + present.format(
                buffer="self._buffer",
                position=f"self._struct_offset + {field.offset}",
            )
        ]

    if field.offset < 4 or field.offset % 2:
        raise GenerationError(
            f"invalid vtable offset {field.offset} for scalar field {field.name!r}"
        )

    default = context.default_expression(field)
    relative = f"{target}_relative"
    return [
        f"{indent}if {field.offset} >= self._vtable_size:",
        f"{indent}    {target} = {default}",
        f"{indent}else:",
        (
            f"{indent}    {relative} = _UINT16.unpack_from("
            f"self._buffer, self._vtable_offset + {field.offset})[0]"
        ),
        f"{indent}    if {relative} == 0:",
        f"{indent}        {target} = {default}",
        (
            f"{indent}    elif {relative} < 4 or "
            f"{relative} > self._object_size - {scalar.size}:"
        ),
        (
            f"{indent}        raise InvalidBufferError("
            '"field lies outside its FlatBuffers table")'
        ),
        f"{indent}    else:",
        f"{indent}        {target} = "
        + present.format(
            buffer="self._buffer",
            position=f"self._table_offset + {relative}",
        ),
    ]


def _cache_slot(field: FieldDefinition) -> str:
    return f"_fb_cached_{_identifier(field.name)}"


def _complex_view_loader(context: _Context, field: FieldDefinition) -> str:
    type_ref = field.type
    if type_ref.base_type is BaseType.STRING:
        return f"self._read_string({field.offset})"
    if type_ref.base_type is BaseType.OBJECT:
        item = context.object_for(type_ref)
        method = "_read_struct" if item.is_struct else "_read_table"
        return f"self.{method}({field.offset}, {context.view_name(item)})"
    if type_ref.base_type is BaseType.VECTOR:
        element = type_ref.element
        if _is_byte_vector(type_ref):
            return f"self._read_byte_vector({field.offset})"
        if element in _SCALARS:
            dtype = _NUMPY_DTYPES[element]
            return f"self._read_numpy_vector({field.offset}, {dtype!r})"
        if element is BaseType.STRING:
            return f"self._read_string_vector({field.offset})"
        if element is BaseType.OBJECT:
            item = context.object_for(type_ref)
            key = context.table_key_field(item)
            if key is not None:
                key_type = (
                    "string"
                    if key.type.base_type is BaseType.STRING
                    else context.scalar_spec(key.type.base_type).runtime_name
                )
                return (
                    f"self._read_table_map({field.offset}, "
                    f"{context.view_name(item)}, {_identifier(key.name)!r}, "
                    f"{key_type!r})"
                )
            method = "_read_struct_vector" if item.is_struct else "_read_table_vector"
            return f"self.{method}({field.offset}, {context.view_name(item)})"
        raise GenerationError(f"unsupported vector element type {element.name}")
    if type_ref.base_type is BaseType.ARRAY:
        element = type_ref.element
        if element in _SCALARS:
            dtype = _NUMPY_DTYPES[element]
            return (
                f"self._read_numpy_array({field.offset}, "
                f"{type_ref.fixed_length}, {dtype!r})"
            )
        if element is BaseType.OBJECT:
            item = context.object_for(type_ref)
            if not item.is_struct:
                raise GenerationError("FlatBuffers arrays may only contain structs")
            return (
                f"self._read_struct_array({field.offset}, "
                f"{type_ref.fixed_length}, {context.view_name(item)})"
            )
        raise GenerationError(f"unsupported array element type {element.name}")
    raise GenerationError(f"unsupported field type {type_ref.base_type.name}")


def _complex_cache_load_lines(
    context: _Context,
    field: FieldDefinition,
    *,
    target: str,
    indent: str,
) -> list[str]:
    """Render a direct per-field slot cache lookup and cold-path load."""

    slot = _cache_slot(field)
    lines = [
        f"{indent}try:",
        f"{indent}    {target} = self.{slot}",
        f"{indent}except AttributeError:",
        f"{indent}    {target} = {_complex_view_loader(context, field)}",
    ]
    lines.extend(_required_field_check(field, target=target, indent=f"{indent}    "))
    lines.append(f"{indent}    self.{slot} = {target}")
    return lines


def _required_field_check(
    field: FieldDefinition,
    *,
    target: str,
    indent: str,
) -> list[str]:
    if not field.required:
        return []
    return [
        f"{indent}if {target} is None:",
        (
            f"{indent}    raise InvalidBufferError("
            f'"required field {field.name!r} is absent")'
        ),
    ]


def _view_return_type(annotation: str, field: FieldDefinition) -> str:
    return annotation if field.required else f"{annotation} | None"


def _complex_view_property(
    context: _Context,
    field: FieldDefinition,
    *,
    name: str | None = None,
) -> list[str]:
    name = _identifier(field.name) if name is None else name
    return_type = _view_return_type(context.view_type(field.type), field)
    return [
        "    @property",
        f"    def {name}(self) -> {return_type}:",
        *_complex_cache_load_lines(
            context,
            field,
            target="value",
            indent="        ",
        ),
        "        return value",
    ]


def _array_view_property(
    context: _Context,
    field: FieldDefinition,
) -> list[str]:
    name = _identifier(field.name)
    return [
        "    @property",
        f"    def {name}(self) -> {context.view_type(field.type)}:",
        *_complex_cache_load_lines(
            context,
            field,
            target="value",
            indent="        ",
        ),
        "        return value",
    ]


def _byte_vector_as_method(field: FieldDefinition) -> list[str]:
    property_name = _identifier(field.name)
    return_type = _view_return_type("_NestedViewT", field)
    cache_key = f"_fb_nested_views:{property_name}"
    lines = [
        f"    def {property_name}_as(",
        "        self,",
        "        view_type: type[_NestedViewT],",
        "        *,",
        "        size_prefixed: bool = False,",
        f"    ) -> {return_type}:",
        f"        payload = self.{property_name}",
    ]
    if not field.required:
        lines.extend(
            [
                "        if payload is None:",
                "            return None",
            ]
        )
    lines.extend(
        [
            "        try:",
            "            cache: dict[tuple[type[_FbTableView], bool], Any] = (",
            f"                self._cache[{cache_key!r}]",
            "            )",
            "        except KeyError:",
            "            cache = {}",
            f"            self._cache[{cache_key!r}] = cache",
            "        key = (view_type, size_prefixed)",
            "        try:",
            "            return cache[key]",
            "        except KeyError:",
            "            value = _decode_flatbuffer(",
            "                payload, type=view_type,",
            "                size_prefixed=size_prefixed,",
            "            )",
            "            cache[key] = value",
            "            return value",
        ]
    )
    return lines


def _raw_property_name(field: FieldDefinition) -> str:
    return f"{_identifier(field.name)}_raw"


def _nested_cache_slot(field: FieldDefinition, *, size_prefixed: bool) -> str:
    prefix = "_fb_nested_prefixed" if size_prefixed else "_fb_nested"
    return f"{prefix}_{_identifier(field.name)}"


def _dynamic_cache_slot(field: FieldDefinition) -> str:
    return f"_fb_dynamic_{_identifier(field.name)}"


def _dynamic_cache_load_lines(
    owner: ObjectDefinition,
    pair: _DynamicPair,
    *,
    target: str,
    indent: str,
) -> list[str]:
    field = pair.value_field
    type_property = _raw_property_name(pair.type_field)
    payload_property = _raw_property_name(field)
    cache_slot = _dynamic_cache_slot(field)
    value_type = _dynamic_value_type_name(owner, pair)
    lines = [
        f"{indent}try:",
        f"{indent}    {target} = self.{cache_slot}",
        f"{indent}except AttributeError:",
        f"{indent}    type_tag = self.{type_property}",
        f"{indent}    payload = self.{payload_property}",
        f"{indent}    if type_tag is None:",
        f"{indent}        if payload is not None:",
        f"{indent}            raise InvalidBufferError(",
        (
            f'{indent}                "dynamic field {field.name!r} has data '
            'without a type tag"'
        ),
        f"{indent}            )",
    ]
    if field.required:
        lines.extend(
            [
                f"{indent}        raise InvalidBufferError(",
                (
                    f'{indent}            "required dynamic field {field.name!r} '
                    'is absent"'
                ),
                f"{indent}        )",
            ]
        )
    else:
        lines.append(f"{indent}        {target} = None")
    lines.extend(
        [
            f"{indent}    elif payload is None:",
            f"{indent}        raise InvalidBufferError(",
            (
                f'{indent}            "dynamic field {field.name!r} type tag '
                'has no data"'
            ),
            f"{indent}        )",
            f"{indent}    else:",
            f"{indent}        {target} = DynamicView(",
            f"{indent}            type_tag, payload, {value_type}",
            f"{indent}        )",
            f"{indent}    self.{cache_slot} = {target}",
        ]
    )
    return lines


def _dynamic_view_property(
    owner: ObjectDefinition,
    pair: _DynamicPair,
) -> list[str]:
    field = pair.value_field
    property_name = _identifier(field.name)
    return_type = _view_return_type("DynamicView", field)
    return [
        "    @property",
        f"    def {property_name}(self) -> {return_type}:",
        *_dynamic_cache_load_lines(
            owner,
            pair,
            target="value",
            indent="        ",
        ),
        "        return value",
    ]


def _nested_cache_load_lines(
    context: _Context,
    field: FieldDefinition,
    nested: ObjectDefinition,
    *,
    target: str,
    indent: str,
    size_prefixed: bool,
) -> list[str]:
    nested_name = context.view_name(nested)
    cache_slot = _nested_cache_slot(field, size_prefixed=size_prefixed)
    payload_property = _raw_property_name(field)
    lines = [
        f"{indent}try:",
        f"{indent}    {target} = self.{cache_slot}",
        f"{indent}except AttributeError:",
        f"{indent}    payload = self.{payload_property}",
    ]
    if not field.required:
        lines.extend(
            [
                f"{indent}    if payload is None:",
                f"{indent}        {target} = None",
                f"{indent}    else:",
            ]
        )
    load_indent = indent if field.required else f"{indent}    "
    lines.extend(
        [
            f"{load_indent}    {target} = _decode_flatbuffer(",
            f"{load_indent}        payload, type={nested_name},",
            f"{load_indent}        size_prefixed={size_prefixed!r},",
            f"{load_indent}    )",
        ]
    )
    lines.append(f"{indent}    self.{cache_slot} = {target}")
    return lines


def _nested_view_members(
    context: _Context,
    field: FieldDefinition,
    nested: ObjectDefinition,
) -> list[str]:
    property_name = _identifier(field.name)
    nested_name = context.view_name(nested)
    return_type = _view_return_type(nested_name, field)
    return [
        "    @property",
        f"    def {property_name}(self) -> {return_type}:",
        *_nested_cache_load_lines(
            context,
            field,
            nested,
            target="value",
            indent="        ",
            size_prefixed=False,
        ),
        "        return value",
        "",
        f"    def {property_name}_view(",
        "        self,",
        "        *,",
        "        size_prefixed: bool = False,",
        f"    ) -> {return_type}:",
        "        if not size_prefixed:",
        f"            return self.{property_name}",
        *_nested_cache_load_lines(
            context,
            field,
            nested,
            target="value",
            indent="        ",
            size_prefixed=True,
        ),
        "        return value",
    ]


def _union_cache_load_lines(
    context: _Context,
    pair: _UnionPair,
    *,
    target: str,
    indent: str,
) -> list[str]:
    field = pair.value_field
    slot = _cache_slot(field)
    property_name = _identifier(field.name)
    dispatch = context.union_dispatch_name(pair.enum)
    annotation = _view_return_type(_union_view_type(context, pair), field)
    lines = [
        f"{indent}try:",
        f"{indent}    {target} = self.{slot}",
        f"{indent}except AttributeError:",
        f"{indent}    {target} = cast(",
        f"{indent}        {annotation},",
        f"{indent}        self._read_union(",
        f"{indent}            {field.offset}, int(self.{property_name}_type), {dispatch}",
        f"{indent}        ),",
        f"{indent}    )",
    ]
    lines.extend(_required_field_check(field, target=target, indent=f"{indent}    "))
    lines.append(f"{indent}    self.{slot} = {target}")
    return lines


def _union_view_property(context: _Context, pair: _UnionPair) -> list[str]:
    field = pair.value_field
    property_name = _identifier(field.name)
    annotation = _view_return_type(_union_view_type(context, pair), field)
    return [
        "    @property",
        f"    def {property_name}(self) -> {annotation}:",
        *_union_cache_load_lines(
            context,
            pair,
            target="value",
            indent="        ",
        ),
        "        return value",
    ]


def _union_vector_cache_load_lines(
    context: _Context,
    pair: _UnionPair,
    *,
    target: str,
    indent: str,
) -> list[str]:
    field = pair.value_field
    type_field = pair.type_field
    slot = _cache_slot(field)
    type_property = _identifier(type_field.name)
    dispatch = context.union_dispatch_name(pair.enum)
    reader, _ = _SCALAR_READERS[pair.enum.underlying_type.base_type]
    lines = [
        f"{indent}try:",
        f"{indent}    {target} = self.{slot}",
        f"{indent}except AttributeError:",
        f"{indent}    types = self.{type_property}",
        f"{indent}    info = self._vector_info({field.offset}, 4)",
        f"{indent}    if types is None and info is None:",
    ]
    if field.required:
        lines.append(
            f"{indent}        raise InvalidBufferError("
            f'"required field {field.name!r} is absent")'
        )
    else:
        lines.append(f"{indent}        {target} = None")
    lines.extend(
        [
            f"{indent}    elif types is None or info is None:",
            (
                f"{indent}        raise InvalidBufferError("
                f'"union vector {field.name!r} type/value presence differs")'
            ),
            f"{indent}    else:",
            f"{indent}        start, length = info",
            f"{indent}        {target} = UnionVector(",
            f"{indent}            self._buffer, types, start, length, {reader}, {dispatch}",
            f"{indent}        )",
            f"{indent}    self.{slot} = {target}",
        ]
    )
    return lines


def _union_vector_property(context: _Context, pair: _UnionPair) -> list[str]:
    field = pair.value_field
    name = _identifier(field.name)
    annotation = _view_return_type(
        f"UnionVector[{_union_view_type(context, pair)} | None]",
        field,
    )
    return [
        "    @property",
        f"    def {name}(self) -> {annotation}:",
        *_union_vector_cache_load_lines(
            context,
            pair,
            target="value",
            indent="        ",
        ),
        "        return value",
    ]


def _render_view_field_property(
    context: _Context,
    item: ObjectDefinition,
    field: FieldDefinition,
    union_pair: _UnionPair | None,
    *,
    raw: bool,
) -> list[str]:
    if union_pair is not None:
        if union_pair.vector:
            return _union_vector_property(context, union_pair)
        return _union_view_property(context, union_pair)
    if raw:
        return _complex_view_property(
            context,
            field,
            name=_raw_property_name(field),
        )
    if field.type.base_type in _SCALARS:
        return _scalar_view_property(context, field, item.is_struct)
    if not item.is_struct:
        return _complex_view_property(context, field)
    if field.type.base_type is BaseType.ARRAY:
        return _array_view_property(context, field)
    if field.type.base_type is not BaseType.OBJECT:
        raise GenerationError(
            f"unsupported struct field type {field.type.base_type.name}"
        )

    nested = context.object_for(field.type)
    if not nested.is_struct:
        raise GenerationError("FlatBuffers structs may only contain structs")
    property_name = _identifier(field.name)
    nested_name = _short_name(nested.name)
    return [
        "    @property",
        f"    def {property_name}(self) -> {nested_name}View:",
        *_complex_cache_load_lines(
            context,
            field,
            target="value",
            indent="        ",
        ),
        "        return value",
    ]


def _render_view(context: _Context, item: ObjectDefinition, root: bool) -> list[str]:
    name = _short_name(item.name)
    base = "_FbStructView" if item.is_struct else "_FbTableView"
    fields = _field_order(item)
    union_pairs = context.union_pairs(item)
    union_pairs_by_value_id = {pair.value_field.id: pair for pair in union_pairs}
    dynamic_pairs = context.dynamic_pairs(item)
    dynamic_pairs_by_value_id = {pair.value_field.id: pair for pair in dynamic_pairs}
    dynamic_pairs_by_type_id = {pair.type_field.id: pair for pair in dynamic_pairs}
    nested_targets = {
        field.id: target
        for field in fields
        if (target := context.nested_target(item, field)) is not None
    }
    raw_field_ids = (
        set(nested_targets)
        | dynamic_pairs_by_value_id.keys()
        | dynamic_pairs_by_type_id.keys()
    )
    cached_fields = [field for field in fields if field.type.base_type not in _SCALARS]
    byte_vector_fields = [
        field
        for field in fields
        if _is_byte_vector(field.type)
        and field.id not in nested_targets
        and field.id not in dynamic_pairs_by_value_id
    ]
    property_names = {_identifier(field.name) for field in fields}
    for field in byte_vector_fields:
        method_name = f"{_identifier(field.name)}_as"
        if method_name in property_names:
            raise GenerationError(
                f"generated byte-vector helper {method_name!r} conflicts with a field"
            )
    for field in fields:
        if field.id in nested_targets:
            method_name = f"{_identifier(field.name)}_view"
            if method_name in property_names:
                raise GenerationError(
                    f"generated nested helper {method_name!r} conflicts with a field"
                )
        if field.id in raw_field_ids:
            raw_name = _raw_property_name(field)
            if raw_name in property_names:
                raise GenerationError(
                    f"generated raw property {raw_name!r} conflicts with a field"
                )
    cache_slots = [_cache_slot(field) for field in cached_fields]
    for field in fields:
        if field.id in nested_targets:
            cache_slots.extend(
                (
                    _nested_cache_slot(field, size_prefixed=False),
                    _nested_cache_slot(field, size_prefixed=True),
                )
            )
    cache_slots.extend(_dynamic_cache_slot(pair.value_field) for pair in dynamic_pairs)
    model_offset = "_struct_offset" if item.is_struct else "_table_offset"
    lines = [f"class {name}View({base}):"]
    lines.extend(_documentation(item.documentation))
    lines.append(f"    __slots__ = {tuple(cache_slots)!r}")
    if item.is_struct:
        lines.append(f"    __flatbuffer_size__ = {item.byte_size}")
    elif root and context.schema.file_identifier is not None:
        lines.append(
            f"    __flatbuffer_identifier__ = {context.schema.file_identifier.encode()!r}"
        )

    for field in fields:
        lines.append("")
        pair = union_pairs_by_value_id.get(field.id)
        lines.extend(
            _render_view_field_property(
                context,
                item,
                field,
                pair,
                raw=field.id in raw_field_ids,
            )
        )

    for field in byte_vector_fields:
        lines.append("")
        lines.extend(_byte_vector_as_method(field))

    for field in fields:
        target = nested_targets.get(field.id)
        if target is not None:
            lines.append("")
            lines.extend(_nested_view_members(context, field, target))

    for pair in dynamic_pairs:
        lines.append("")
        lines.extend(_dynamic_view_property(item, pair))

    lines.extend(
        (
            "",
            "    @overload",
            "    def to_model(",
            "        self,",
            "        *,",
            "        dynamic_overrides: DynamicModelOverrides | None = None,",
            f"    ) -> {name}: ...",
            "",
            "    @overload",
            f"    def to_model[_ModelT: {name}](",
            "        self,",
            "        model_type: type[_ModelT],",
            "        *,",
            "        dynamic_overrides: DynamicModelOverrides | None = None,",
            "    ) -> _ModelT: ...",
            "",
            "    def to_model(",
            "        self,",
            f"        model_type: type[{name}] = {name},",
            "        *,",
            "        dynamic_overrides: DynamicModelOverrides | None = None,",
            f"    ) -> {name}:",
            f"        if model_type is {name} and dynamic_overrides is None:",
            "            return _FB_NATIVE_MODULE.unpack_view(",
            f"                {item.name!r},",
            "                self._buffer,",
            f"                self.{model_offset},",
            "            )",
            f"        native_types = None if model_type is {name} else _resolve_model_types(",
            f"            _FB_NATIVE_MODULE, {name}, model_type",
            "        )",
            "        return _FB_NATIVE_MODULE.unpack_view(",
            f"            {item.name!r},",
            "            self._buffer,",
            f"            self.{model_offset},",
            "            model_types=native_types,",
            "            dynamic_overrides=dynamic_overrides,",
            "        )",
        )
    )
    return lines


def _native_plan_default(field: FieldDefinition) -> bool | int | float | None:
    if field.optional:
        return None
    if field.type.base_type is BaseType.BOOL:
        return bool(field.default_integer)
    if field.type.base_type in (BaseType.FLOAT, BaseType.DOUBLE):
        return field.default_real
    if field.type.base_type in _SCALARS:
        return field.default_integer
    return None


def _native_field_plan(
    context: _Context,
    owner: ObjectDefinition,
    field: FieldDefinition,
    union_pair: _UnionPair | None,
    dynamic_pair: _DynamicPair | None,
) -> dict[str, object]:
    if field.offset64:
        raise GenerationError(
            f"64-bit offset field {owner.name}.{field.name} is unsupported"
        )
    type_ref = field.type
    plan: dict[str, object] = {
        "name": _identifier(field.name),
        "slot": field.id,
        "offset": field.offset,
        "optional": field.optional,
        "required": field.required,
        "default": _native_plan_default(field),
        "serde_nullable": field.optional,
    }
    if field.key:
        plan["key"] = True
    if union_pair is not None:
        plan.update(
            kind="union_vector" if union_pair.vector else "union",
            type_slot=union_pair.type_field.id,
            type_scalar=context.scalar_spec(
                union_pair.enum.underlying_type.base_type
            ).runtime_name,
            arms=[
                {"tag": arm.tag, "target": arm.object.name} for arm in union_pair.arms
            ],
        )
        if union_pair.vector:
            plan["serde_element_nullable"] = True
        return plan
    if dynamic_pair is not None:
        plan.update(
            kind="dynamic",
            type_slot=dynamic_pair.type_field.id,
            allowed_prefix=dynamic_pair.allowed_prefix,
            dynamic_type=_dynamic_value_type_key(owner, dynamic_pair),
        )
        return plan
    nested = context.nested_target(owner, field)
    if nested is not None:
        plan.update(kind="nested", target=nested.name)
        return plan
    if type_ref.base_type in _SCALARS:
        plan.update(
            kind="scalar",
            scalar=context.scalar_spec(type_ref.base_type).runtime_name,
        )
        enum = context.enum_for(type_ref)
        if enum is not None:
            plan["enum_type"] = enum.name
    elif type_ref.base_type is BaseType.STRING:
        plan["kind"] = "string"
    elif type_ref.base_type is BaseType.OBJECT:
        target = context.object_for(type_ref)
        plan.update(
            kind="struct" if target.is_struct else "table",
            target=target.name,
        )
    elif type_ref.base_type is BaseType.VECTOR:
        if _is_byte_vector(type_ref):
            plan["kind"] = "vector_byte"
        elif type_ref.element in _SCALARS:
            plan.update(
                kind="vector_scalar",
                scalar=context.scalar_spec(type_ref.element).runtime_name,
            )
            enum = context.enum_for(type_ref)
            if enum is not None:
                plan["enum_type"] = enum.name
        elif type_ref.element is BaseType.STRING:
            plan["kind"] = "vector_string"
        elif type_ref.element is BaseType.OBJECT:
            target = context.object_for(type_ref)
            plan.update(
                kind="vector_struct" if target.is_struct else "vector_table",
                target=target.name,
            )
        else:  # pragma: no cover - rejected by earlier generation checks
            raise GenerationError(
                f"unsupported native vector element {type_ref.element.name}"
            )
    elif type_ref.base_type is BaseType.ARRAY:
        plan.update(
            fixed_length=type_ref.fixed_length,
            element_size=type_ref.element_size,
        )
        if type_ref.element in _SCALARS:
            plan.update(
                kind="array_scalar",
                scalar=context.scalar_spec(type_ref.element).runtime_name,
            )
            enum = context.enum_for(type_ref)
            if enum is not None:
                plan["enum_type"] = enum.name
        elif type_ref.element is BaseType.OBJECT:
            target = context.object_for(type_ref)
            if not target.is_struct:
                raise GenerationError("FlatBuffers arrays may only contain structs")
            plan.update(
                kind="array_struct",
                target=target.name,
                element_size=target.byte_size,
            )
        else:
            raise GenerationError(
                f"unsupported native array element {type_ref.element.name}"
            )
    else:  # pragma: no cover - rejected by earlier generation checks
        raise GenerationError(
            f"unsupported native field type {type_ref.base_type.name}"
        )
    return plan


def _native_module_plan_bytes(context: _Context) -> bytes:
    objects: list[dict[str, object]] = []
    for item in context.schema.objects:
        if item.name not in context.reachable_object_names:
            continue
        union_pairs = context.union_pairs(item)
        dynamic_pairs = context.dynamic_pairs(item)
        union_by_value = {pair.value_field.id: pair for pair in union_pairs}
        dynamic_by_value = {pair.value_field.id: pair for pair in dynamic_pairs}
        hidden_type_field_ids = _hidden_type_field_ids(
            union_pairs,
            dynamic_pairs,
        )
        model_fields = [
            field
            for field in _field_order(item)
            if field.id not in hidden_type_field_ids
        ]
        fields = [
            _native_field_plan(
                context,
                item,
                field,
                union_by_value.get(field.id),
                dynamic_by_value.get(field.id),
            )
            for field in model_fields
        ]
        is_union_arm = context.is_union_arm(item)
        objects.append(
            {
                "name": item.name,
                "is_struct": item.is_struct,
                "byte_size": item.byte_size,
                "min_alignment": item.min_alignment,
                "fields": fields,
                "serde_fields": [
                    {
                        "attr_name": _identifier(field.name),
                        "encode_name": field.name,
                    }
                    for field in model_fields
                ],
                "serde_tag_field": _MSGSPEC_TAG_FIELD if is_union_arm else None,
                "serde_tag": item.name if is_union_arm else None,
            }
        )
    return msgspec.msgpack.encode({"version": 2, "objects": objects})


def _local_root(
    schema: Schema,
    local_names: frozenset[str],
) -> ObjectDefinition | None:
    if schema.root_table is None:
        return None
    root = schema.object(schema.root_table)
    return root if root.name in local_names else None


def _dynamic_extension_enabled(
    local_objects: Sequence[ObjectDefinition],
    root: ObjectDefinition | None,
) -> bool:
    enabled = False
    for item in local_objects:
        if not _has_marker_attribute(item, "dynamic_extension"):
            continue
        if item.is_struct or item is not root:
            raise GenerationError(
                f"dynamic extension {item.name} must be this file's root table"
            )
        enabled = True
    return enabled


def _reexported_symbols(
    object_imports: dict[str, set[str]],
    enum_imports: dict[str, set[str]],
    local_symbols: set[str],
) -> dict[str, str | None]:
    reexports: dict[str, str | None] = {}
    for module in sorted(object_imports.keys() | enum_imports.keys()):
        names = object_imports.get(module, set()) | enum_imports.get(module, set())
        for name in names - local_symbols:
            if name not in reexports:
                reexports[name] = module
            elif reexports[name] != module:
                reexports[name] = None
    return reexports


def _bound_type_names(
    context: _Context,
    dynamic_field_pairs: Sequence[tuple[ObjectDefinition, _DynamicPair]],
) -> dict[str, str]:
    bound_types = {
        item.name: context.model_name(item)
        for item in context.schema.objects
        if item.name in context.reachable_object_names
    }
    bound_types.update(
        {
            enum.name: context.enum_name(enum)
            for enum in context.schema.enums
            if enum.name in context.reachable_enum_names
        }
    )
    bound_types.update(
        {
            _dynamic_value_type_key(item, pair): _dynamic_value_type_name(item, pair)
            for item, pair in dynamic_field_pairs
        }
    )
    return bound_types


def render_module(
    schema: Schema,
    declaration_file: str,
    *,
    package_prefix: Iterable[str] = (),
    definition_names: frozenset[str] | None = None,
    gen_onefile: bool = False,
) -> str:
    """Render Python source for definitions from one declaring file.

    Args:
        schema: The normalized schema to render.
        declaration_file: The source filename recorded in the schema, including
            its leading ``//``.
        package_prefix: Optional Python package components prepended to generated
            imports.
        definition_names: Fully qualified definitions to render. All definitions
            from ``declaration_file`` are rendered by default.
        gen_onefile: Whether all definitions share one generated module.

    Returns:
        A complete generated Python module.

    Raises:
        GenerationError: The selection is empty, ambiguous, or unsupported.

    Example:
        Render every definition declared by one schema file:

        >>> source = render_module(schema, "//schemas/monster.fbs")
        >>> source.startswith("# Generated by msgspec-serde")
        True
    """

    prefix = tuple(_snake_case(part) for part in package_prefix)

    def is_local(item: ObjectDefinition | EnumDefinition) -> bool:
        return item.declaration_file == declaration_file and (
            definition_names is None or item.name in definition_names
        )

    local_objects = [item for item in schema.objects if is_local(item)]
    local_enums = [item for item in schema.enums if is_local(item)]
    local_tables = [item for item in local_objects if not item.is_struct]
    local_structs = [item for item in local_objects if item.is_struct]
    local_fields = [(item, field) for item in local_objects for field in item.fields]
    local_definitions = [*local_objects, *local_enums]
    if not local_definitions:
        raise GenerationError(f"no definitions declared in {declaration_file!r}")
    _validate_member_names(local_objects, local_enums)
    local_symbols = _local_symbols(local_objects, local_enums)
    local_names = frozenset(item.name for item in local_definitions)
    context = _Context(
        schema,
        prefix,
        local_names,
        gen_onefile,
    )
    dynamic_field_pairs = [
        (item, pair) for item in local_objects for pair in context.dynamic_pairs(item)
    ]
    dynamic_value_field_ids = {
        (item.name, pair.value_field.id) for item, pair in dynamic_field_pairs
    }
    has_dynamic = bool(dynamic_field_pairs)
    has_byte_vector_helpers = any(
        _is_byte_vector(field.type)
        and context.nested_target(item, field) is None
        and (item.name, field.id) not in dynamic_value_field_ids
        for item, field in local_fields
    )
    has_nested_flatbuffers = any(
        context.nested_target(item, field) is not None for item, field in local_fields
    )
    needs_flatbuffer_decoder = has_byte_vector_helpers or has_nested_flatbuffers
    union_pairs = [pair for item in local_objects for pair in context.union_pairs(item)]
    has_union_definitions = any(item.is_union for item in local_enums)
    has_scalar_unions = any(not pair.vector for pair in union_pairs)
    has_union_vectors = any(pair.vector for pair in union_pairs)
    has_numpy_fields = any(
        _is_numpy_model_field(context, field) for _, field in local_fields
    )
    has_string_vectors = any(
        field.type.base_type is BaseType.VECTOR
        and field.type.element is BaseType.STRING
        for _, field in local_fields
    )
    vector_object_targets = [
        context.object_for(field.type)
        for _, field in local_fields
        if field.type.base_type is BaseType.VECTOR
        and field.type.element is BaseType.OBJECT
    ]
    array_object_targets = [
        context.object_for(field.type)
        for _, field in local_fields
        if field.type.base_type is BaseType.ARRAY
        and field.type.element is BaseType.OBJECT
    ]
    table_vector_keys = [
        context.key_field(target)
        for target in vector_object_targets
        if not target.is_struct
    ]
    has_struct_vectors = any(
        target.is_struct for target in vector_object_targets
    ) or any(target.is_struct for target in array_object_targets)
    has_table_vectors = any(key is None for key in table_vector_keys)
    has_table_maps = any(key is not None for key in table_vector_keys)
    needs_invalid_buffer_error = any(
        (
            any(
                field.type.base_type in _SCALARS or field.required
                for field in _field_order(item)
            )
            or context.union_pairs(item)
            or context.dynamic_pairs(item)
        )
        for item in local_tables
    )
    typing_imports = {"overload"} if local_objects else set()
    if has_byte_vector_helpers:
        typing_imports.update(("Any", "TypeVar"))
    if has_scalar_unions:
        typing_imports.add("cast")

    root = _local_root(schema, local_names)
    dynamic_extension = _dynamic_extension_enabled(local_objects, root)

    object_imports, enum_imports = context.referenced_definitions(
        local_objects,
        local_enums,
    )
    import_modules = set(object_imports) | set(enum_imports)
    enum_dependency_modules = set(enum_imports)
    dynamic_value_names = [
        _dynamic_value_type_name(item, pair) for item, pair in dynamic_field_pairs
    ]
    for dynamic_name in dynamic_value_names:
        if dynamic_name in local_symbols:
            raise GenerationError(
                f"generated dynamic value type {dynamic_name!r} conflicts with "
                "another generated symbol"
            )
        local_symbols.add(dynamic_name)
    reexports = _reexported_symbols(
        object_imports,
        enum_imports,
        local_symbols,
    )
    scalar_readers = {
        _SCALAR_READERS[field.type.base_type]
        for _, field in local_fields
        if field.type.base_type in _SCALARS
    }
    for pair in union_pairs:
        if pair.vector:
            scalar_readers.add(_SCALAR_READERS[pair.enum.underlying_type.base_type])
    if any(
        any(field.type.base_type in _SCALARS for field in item.fields)
        for item in local_tables
    ):
        scalar_readers.add(("_UINT16", "<H"))
    runtime_imports = []
    if local_objects:
        runtime_imports.append("DynamicModelOverrides")
    if needs_invalid_buffer_error:
        runtime_imports.append("InvalidBufferError")
    if local_enums:
        runtime_imports.append("OpenIntEnum as _FbOpenIntEnum")
    if has_string_vectors:
        runtime_imports.append("StringVector")
    if has_struct_vectors:
        runtime_imports.append("StructVector")
    if local_structs:
        runtime_imports.append("StructView as _FbStructView")
    if has_table_vectors:
        runtime_imports.append("TableVector")
    if has_table_maps:
        runtime_imports.append("TableMap")
    if local_tables:
        runtime_imports.append("TableView as _FbTableView")
    if has_dynamic:
        runtime_imports.extend(("DynamicValue as _FbDynamicValue", "DynamicView"))
    if dynamic_extension:
        runtime_imports.append("register_dynamic_type as _register_dynamic_type")
    if has_union_definitions:
        runtime_imports.append("UnionDispatch as _FbUnionDispatch")
    if has_union_vectors:
        runtime_imports.append("UnionVector")
    standard_imports = []
    if scalar_readers:
        standard_imports.append("import struct")
    if typing_imports:
        standard_imports.append(
            f"from typing import {', '.join(sorted(typing_imports))}"
        )
    third_party_imports = []
    if local_objects:
        third_party_imports.append("import msgspec")
    if has_numpy_fields:
        third_party_imports.extend(("import numpy as np", "import numpy.typing as npt"))

    lines = [
        _GENERATED_HEADER,
        f"# Source: {declaration_file}",
        "from __future__ import annotations",
    ]
    if standard_imports:
        lines.extend(("", *standard_imports))
    if third_party_imports:
        lines.extend(("", *third_party_imports))
    lines.extend(
        (
            "",
            "from msgspec_serde import _check_generated_code_version",
            "",
            f"__msgspec_serde_generated_version__ = {_GENERATOR_VERSION!r}",
            "_check_generated_code_version(__msgspec_serde_generated_version__)",
            "",
            "from msgspec_serde import (  # noqa: E402",
            *(f"    {name}," for name in runtime_imports),
            ")",
        )
    )
    if local_objects:
        lines.extend(
            (
                "from msgspec_serde._models import resolve_model_types as _resolve_model_types  # noqa: E402",
                "from msgspec_serde._native import NativePlan as _NativePlan  # noqa: E402",
            )
        )
    if needs_flatbuffer_decoder:
        lines.append(
            "from msgspec_serde._flatbuffer import decode as _decode_flatbuffer  # noqa: E402"
        )
    if local_tables:
        lines.append(
            "from msgspec_serde._flatbuffer import register_type as _register_flatbuffer_type  # noqa: E402"
        )
    if enum_dependency_modules:
        lines.append("")
        lines.extend(
            f"import {module} as {context.module_alias(module)}"
            for module in sorted(enum_dependency_modules)
        )
    if has_byte_vector_helpers:
        lines.extend(("", '_NestedViewT = TypeVar("_NestedViewT", bound=_FbTableView)'))
    if scalar_readers:
        lines.append("")
    for reader, fmt in sorted(scalar_readers):
        lines.append(f"{reader} = struct.Struct({fmt!r})")
    if local_objects:
        lines.extend(
            (
                "",
                f"_FB_NATIVE_MODULE = _NativePlan({_native_module_plan_bytes(context)!r})",
            )
        )

    for item in local_enums:
        lines.extend(("", "", *_render_enum(context, item)))
    for item, pair in dynamic_field_pairs:
        lines.extend(("", "", *_render_dynamic_value_type(item, pair)))
    for item in local_objects:
        lines.extend(("", "", *_render_model(context, item)))
    for item in local_objects:
        lines.extend(("", "", *_render_view(context, item, item is root)))
    object_dependency_modules = import_modules - enum_dependency_modules
    if object_dependency_modules:
        lines.extend(("", ""))
        lines.extend(
            f"import {module} as {context.module_alias(module)}"
            for module in sorted(object_dependency_modules)
        )
    reexport_lines = [
        f"{name} = {context.module_alias(module)}.{name}"
        for name, module in sorted(reexports.items())
        if module is not None
    ]
    if reexport_lines:
        lines.extend(("", "", *reexport_lines))
    for item in local_enums:
        if item.is_union:
            lines.extend(("", "", *_render_union_dispatch(context, item)))
    bound_types = (
        _bound_type_names(context, dynamic_field_pairs) if local_objects else {}
    )
    if bound_types:
        lines.extend(("", "", "_FB_NATIVE_MODULE.bind_types({"))
        lines.extend(
            f"    {name!r}: {type_name},"
            for name, type_name in sorted(bound_types.items())
        )
        lines.append("})")
    for item in local_tables:
        identifier = (
            repr(context.schema.file_identifier)
            if item is root and context.schema.file_identifier is not None
            else "None"
        )
        lines.extend(
            (
                "",
                "",
                f"_register_flatbuffer_type({_short_name(item.name)}, _FB_NATIVE_MODULE, {item.name!r}, {identifier})",
            )
        )
    if dynamic_extension and root is not None:
        root_name = _short_name(root.name)
        lines.extend(
            (
                "",
                "",
                f"_register_dynamic_type({root.name!r}, {root_name}, {root_name}View)",
            )
        )

    exported = [
        *(_short_name(item.name) for item in local_enums),
        *dynamic_value_names,
        *(
            name
            for item in local_objects
            for name in (_short_name(item.name), f"{_short_name(item.name)}View")
        ),
    ]
    lines.extend(("", "", f"__all__ = {exported!r}", ""))
    return "\n".join(lines)


def _source_declaration(source: Path, project_root: Path) -> str:
    try:
        relative = source.relative_to(project_root)
    except ValueError as error:
        raise GenerationError(
            f"schema {source} is outside project root {project_root}"
        ) from error
    return f"//{relative.as_posix()}"


def generate(
    schema_path: StrPath,
    output_dir: StrPath,
    *,
    include_dirs: Iterable[StrPath] = (),
    flatc: StrPath = "flatc",
    project_root: StrPath | None = None,
    package: str | None = None,
    gen_onefile: bool = False,
) -> Path:
    """Generate Python modules from a FlatBuffers IDL file.

    Args:
        schema_path: The ``.fbs`` file to compile and generate.
        output_dir: The directory that receives generated Python packages.
        include_dirs: Additional directories searched for included schemas.
        flatc: The ``flatc`` executable name or path.
        project_root: The root used for filenames stored by ``flatc``. The
            schema's parent directory is used by default.
        package: An optional Python package prefix.
        gen_onefile: Whether to place all definitions from the schema in one
            module.

    Returns:
        The generated module path for the root definition, or the first module
        when the schema has no root table.

    Raises:
        FlatcError: The schema compiler fails.
        GenerationError: The schema cannot be represented or a generated path
            would overwrite a non-generated file.
        OSError: An input cannot be read or an output cannot be written.

    Example:
        Generate importable modules beneath ``generated``:

        >>> module_path = generate(
        ...     "schemas/monster.fbs",
        ...     "generated",
        ...     package="models",
        ... )
        >>> module_path.suffix
        '.py'
    """

    source = Path(schema_path).resolve()
    root = source.parent if project_root is None else Path(project_root).resolve()
    schema = compile_schema(
        source,
        include_dirs=include_dirs,
        flatc=flatc,
        project_root=root,
    )
    declaration_file = _source_declaration(source, root)
    definitions = [
        item
        for item in [*schema.objects, *schema.enums]
        if item.declaration_file == declaration_file
    ]
    if not definitions:
        raise GenerationError(
            f"compiled schema does not contain declarations for {declaration_file}"
        )

    prefix = tuple(part for part in (package or "").split(".") if part)
    output_root = Path(output_dir).resolve()
    prefix_parts = tuple(_snake_case(part) for part in prefix)
    if gen_onefile:
        module_specs: list[tuple[str | None, tuple[str, ...], str]] = [
            (None, (), _snake_case(source.stem))
        ]
    else:
        module_specs = [
            (
                item.name,
                _namespace(item.name),
                _snake_case(_short_name(item.name)),
            )
            for item in sorted(definitions, key=lambda item: item.name)
        ]
    targets: dict[Path, str] = {}
    rendered_modules: list[tuple[str | None, Path, str]] = []
    for definition_name, namespace_parts, module_name in module_specs:
        package_parts = (
            *prefix_parts,
            *(_snake_case(part) for part in namespace_parts),
        )
        target = output_root.joinpath(*package_parts, f"{module_name}.py")
        source_name = definition_name or declaration_file
        previous = targets.get(target)
        if previous is not None:
            raise GenerationError(
                f"definitions {previous!r} and {source_name!r} both generate "
                f"module {target.relative_to(output_root)}"
            )
        targets[target] = source_name
        selected_names = (
            None if definition_name is None else frozenset((definition_name,))
        )
        source_text = render_module(
            schema,
            declaration_file,
            package_prefix=prefix,
            definition_names=selected_names,
            gen_onefile=gen_onefile,
        )
        rendered_modules.append((definition_name, target, source_text))

    expected_header = [_GENERATED_HEADER, f"# Source: {declaration_file}"]
    for _, target, _ in rendered_modules:
        if target.exists():
            actual_header = target.read_text(encoding="utf-8").splitlines()[:2]
            if actual_header != expected_header:
                raise GenerationError(
                    f"refusing to overwrite non-generated file: {target}"
                )

    initialized_packages: set[Path] = set()
    for _, target, source_text in rendered_modules:
        target.parent.mkdir(parents=True, exist_ok=True)
        relative_parent = target.parent.relative_to(output_root)
        current = output_root
        for part in relative_parent.parts:
            current /= part
            if current in initialized_packages:
                continue
            init = current / "__init__.py"
            if not init.exists():
                init.write_text("", encoding="utf-8")
            initialized_packages.add(current)
        target.write_text(source_text, encoding="utf-8")

    if gen_onefile or schema.root_table is None:
        return rendered_modules[0][1]
    return next(
        target
        for definition_name, target, _ in rendered_modules
        if definition_name == schema.root_table
    )


__all__ = ["GenerationError", "generate", "render_module"]
